// @generated by generate_review_session_contract; do not edit.

export type JsonSchema =
  | boolean
  | {
      $ref?: string
      allOf?: JsonSchema[]
      anyOf?: JsonSchema[]
      oneOf?: JsonSchema[]
      const?: unknown
      enum?: unknown[]
      format?: string
      type?: string | string[]
      properties?: Record<string, JsonSchema>
      required?: string[]
      additionalProperties?: boolean | JsonSchema
      items?: JsonSchema
      minItems?: number
      maxItems?: number
      uniqueItems?: boolean
      minLength?: number
      maxLength?: number
      pattern?: string
      minimum?: number
      maximum?: number
    }

// `uint` is what schemars emits for a Rust `usize`, so it reaches the schema
// whenever a contract field is sized by the host platform rather than by the
// wire. It is bounded here like `uint64`: JSON carries no integer wider than
// the safe range regardless of what the producer's pointer width was.
const integerFormatBounds: Readonly<Record<string, readonly [number, number]>> =
  {
    int8: [-128, 127],
    uint8: [0, 255],
    int16: [-32_768, 32_767],
    uint16: [0, 65_535],
    int32: [-2_147_483_648, 2_147_483_647],
    uint: [0, Number.MAX_SAFE_INTEGER],
    uint32: [0, 4_294_967_295],
    uint64: [0, Number.MAX_SAFE_INTEGER],
  }

export class ContractDecodeError extends Error {
  constructor(
    readonly path: string,
    message: string,
  ) {
    super(`${path}: ${message}`)
    this.name = "ContractDecodeError"
  }
}

export function validateContract(root: JsonSchema, value: unknown): void {
  validate(root, value, "$", root)
}

export function validateContractDefinition(
  root: JsonSchema,
  name: string,
  value: unknown,
): void {
  validate({ $ref: `#/$defs/${name}` }, value, "$", root)
}

export function requireSortedUnique(
  values: readonly string[],
  path: string,
): void {
  if (values.some((value, index) => index > 0 && values[index - 1]! >= value)) {
    throw new ContractDecodeError(path, "must be sorted and unique")
  }
}

export function requireUnique(values: readonly string[], path: string): void {
  if (new Set(values).size !== values.length) {
    throw new ContractDecodeError(path, "must be unique")
  }
}

export function compareAscii(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0
}

export function sameString(left: string, right: string): boolean {
  return left === right
}

export async function assertDigest(
  actual: string,
  content: unknown,
  path: string,
): Promise<void> {
  if (actual !== (await sha256(content))) {
    throw new ContractDecodeError(path, "does not match content")
  }
}

export async function sha256(value: unknown): Promise<string> {
  const bytes = new TextEncoder().encode(canonicalJson(value))
  const digest = await globalThis.crypto.subtle.digest("SHA-256", bytes)
  return `sha256:${[...new Uint8Array(digest)]
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("")}`
}

export function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`
  if (isObject(value)) {
    return `{${Object.keys(value)
      .sort()
      .map((key) => {
        requireWellFormedUnicode(key)
        return `${JSON.stringify(key)}:${canonicalJson(value[key])}`
      })
      .join(",")}}`
  }
  if (typeof value === "string") requireWellFormedUnicode(value)
  const encoded = JSON.stringify(value)
  if (encoded === undefined)
    throw new Error("contract values cannot contain undefined")
  return encoded
}

export function sameCanonicalJson(left: unknown, right: unknown): boolean {
  return canonicalJson(left) === canonicalJson(right)
}

function requireWellFormedUnicode(value: string): void {
  for (let index = 0; index < value.length; index += 1) {
    const codeUnit = value.charCodeAt(index)
    if (codeUnit >= 0xd800 && codeUnit <= 0xdbff) {
      const trailing = value.charCodeAt(index + 1)
      if (index + 1 >= value.length || trailing < 0xdc00 || trailing > 0xdfff) {
        throw new ContractDecodeError(
          "$",
          "contains an unpaired Unicode surrogate",
        )
      }
      index += 1
    } else if (codeUnit >= 0xdc00 && codeUnit <= 0xdfff) {
      throw new ContractDecodeError(
        "$",
        "contains an unpaired Unicode surrogate",
      )
    }
  }
}

function validate(
  rule: JsonSchema,
  value: unknown,
  path: string,
  root: JsonSchema,
): void {
  if (rule === true) return
  if (rule === false) throw new ContractDecodeError(path, "value is forbidden")
  if (rule.$ref !== undefined) {
    validate(resolveReference(root, rule.$ref), value, path, root)
    return
  }
  if (rule.allOf !== undefined) {
    for (const member of rule.allOf) validate(member, value, path, root)
  }
  if (
    rule.anyOf !== undefined &&
    !rule.anyOf.some((member) => accepts(member, value, root))
  ) {
    throw new ContractDecodeError(path, "does not match any allowed shape")
  }
  if (rule.oneOf !== undefined) {
    const matches = rule.oneOf.filter((member) =>
      accepts(member, value, root),
    ).length
    if (matches !== 1)
      throw new ContractDecodeError(path, `matches ${matches} union variants`)
  }
  if ("const" in rule && !sameJson(value, rule.const)) {
    throw new ContractDecodeError(
      path,
      `must equal ${JSON.stringify(rule.const)}`,
    )
  }
  if (
    rule.enum !== undefined &&
    !rule.enum.some((member) => sameJson(value, member))
  ) {
    throw new ContractDecodeError(path, "is not an allowed value")
  }

  const allowedTypes = typeof rule.type === "string" ? [rule.type] : rule.type
  if (
    allowedTypes !== undefined &&
    !allowedTypes.some((type) => hasJsonType(value, type))
  ) {
    throw new ContractDecodeError(path, `must be ${allowedTypes.join(" or ")}`)
  }
  validateString(rule, value, path)
  validateNumber(rule, value, path)
  validateArray(rule, value, path, root)
  validateObject(rule, value, path, root)
}

function validateString(
  rule: Exclude<JsonSchema, boolean>,
  value: unknown,
  path: string,
): void {
  if (typeof value !== "string") return
  requireWellFormedUnicode(value)
  if (rule.minLength !== undefined && value.length < rule.minLength) {
    throw new ContractDecodeError(
      path,
      `must contain at least ${rule.minLength} characters`,
    )
  }
  if (rule.maxLength !== undefined && value.length > rule.maxLength) {
    throw new ContractDecodeError(
      path,
      `must contain at most ${rule.maxLength} characters`,
    )
  }
  if (rule.pattern !== undefined) {
    const match = new RegExp(rule.pattern, "u").exec(value)
    if (match === null || match.index !== 0 || match[0] !== value) {
      throw new ContractDecodeError(
        path,
        "does not fully match the required pattern",
      )
    }
  }
}

function validateNumber(
  rule: Exclude<JsonSchema, boolean>,
  value: unknown,
  path: string,
): void {
  if (typeof value !== "number") return
  const formatBounds =
    rule.format === undefined ? undefined : integerFormatBounds[rule.format]
  if (
    rule.format !== undefined &&
    rule.format !== "double" &&
    formatBounds === undefined
  ) {
    throw new Error(`unsupported numeric JSON Schema format ${rule.format}`)
  }
  if (
    formatBounds !== undefined &&
    (value < formatBounds[0] || value > formatBounds[1])
  ) {
    throw new ContractDecodeError(
      path,
      `must fit the ${rule.format} range ${formatBounds[0]} through ${formatBounds[1]}`,
    )
  }
  if (rule.minimum !== undefined && value < rule.minimum) {
    throw new ContractDecodeError(path, `must be at least ${rule.minimum}`)
  }
  if (rule.maximum !== undefined && value > rule.maximum) {
    throw new ContractDecodeError(path, `must be at most ${rule.maximum}`)
  }
}

function validateArray(
  rule: Exclude<JsonSchema, boolean>,
  value: unknown,
  path: string,
  root: JsonSchema,
): void {
  if (!Array.isArray(value)) return
  if (rule.minItems !== undefined && value.length < rule.minItems) {
    throw new ContractDecodeError(
      path,
      `must contain at least ${rule.minItems} items`,
    )
  }
  if (rule.maxItems !== undefined && value.length > rule.maxItems) {
    throw new ContractDecodeError(
      path,
      `must contain at most ${rule.maxItems} items`,
    )
  }
  if (
    rule.uniqueItems === true &&
    new Set(value.map((item) => JSON.stringify(item))).size !== value.length
  ) {
    throw new ContractDecodeError(path, "must contain unique items")
  }
  if (rule.items !== undefined) {
    value.forEach((item, index) =>
      validate(rule.items!, item, `${path}[${index}]`, root),
    )
  }
}

function validateObject(
  rule: Exclude<JsonSchema, boolean>,
  value: unknown,
  path: string,
  root: JsonSchema,
): void {
  if (!isObject(value)) return
  const properties = rule.properties ?? {}
  for (const required of rule.required ?? []) {
    if (!(required in value))
      throw new ContractDecodeError(`${path}.${required}`, "is required")
  }
  for (const [key, member] of Object.entries(value)) {
    const propertyRule = properties[key]
    if (propertyRule !== undefined) {
      validate(propertyRule, member, `${path}.${key}`, root)
    } else if (rule.additionalProperties === false) {
      throw new ContractDecodeError(`${path}.${key}`, "is not allowed")
    } else if (typeof rule.additionalProperties === "object") {
      validate(rule.additionalProperties, member, `${path}.${key}`, root)
    }
  }
}

function accepts(rule: JsonSchema, value: unknown, root: JsonSchema): boolean {
  try {
    validate(rule, value, "$", root)
    return true
  } catch (error) {
    if (error instanceof ContractDecodeError) return false
    throw error
  }
}

function resolveReference(root: JsonSchema, reference: string): JsonSchema {
  if (!reference.startsWith("#/"))
    throw new Error(`unsupported schema reference ${reference}`)
  let current: unknown = root
  for (const encodedPart of reference.slice(2).split("/")) {
    const part = encodedPart.replaceAll("~1", "/").replaceAll("~0", "~")
    if (!isObject(current) || !(part in current)) {
      throw new Error(`unresolved schema reference ${reference}`)
    }
    current = current[part]
  }
  if (typeof current === "boolean" || isObject(current)) return current
  throw new Error(`invalid schema reference ${reference}`)
}

function hasJsonType(value: unknown, type: string): boolean {
  switch (type) {
    case "null":
      return value === null
    case "boolean":
      return typeof value === "boolean"
    case "number":
      return typeof value === "number" && Number.isFinite(value)
    case "integer":
      return typeof value === "number" && Number.isSafeInteger(value)
    case "string":
      return typeof value === "string"
    case "array":
      return Array.isArray(value)
    case "object":
      return isObject(value)
    default:
      throw new Error(`unsupported JSON Schema type ${type}`)
  }
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

export function sameJson(left: unknown, right: unknown): boolean {
  return JSON.stringify(left) === JSON.stringify(right)
}
