// @generated by generate_review_session_contract; do not edit.

import { expect, test } from "vitest"

import {
  commands,
  ContractDecodeError,
  coreContract,
  decodeEvidenceEntry,
  decodeDailyCoachingDashboardState,
  decodeImportedGame,
  decodeImportedGameListPage,
  decodeReviewedGameSearchResult,
  decodeMoveSequencePresentation,
  decodePositionSnapshot,
  decodeReviewSessionCommandEnvelope,
  decodeReviewSessionCoreContract,
  decodeReviewSessionEventEnvelope,
  decodeReviewSessionEvidencePacket,
  decodeGameReviewSnapshot,
  decodeReviewMomentSnapshot,
  decodeReviewSessionPresentation,
  decodeReviewSessionPresentationAddition,
  evidencePacket,
  events,
  importedGame,
  positionSnapshot,
} from "./index.js"

test("rejects a profile-unavailable lead with a reachable connection", () => {
  expect(() =>
    decodeDailyCoachingDashboardState({
      archive: [],
      connections: [
        {
          canonicalUrl: "https://lichess.org/@/PlayerOne",
          provider: "lichess",
          status: "connected",
          username: "PlayerOne",
        },
      ],
      enabled: true,
      hostConnections: [],
      kind: "connected",
      lead: { kind: "profileUnavailable" },
      timezone: "UTC",
    }),
  ).toThrow(/must be profileUnavailable exactly when/)
})

test("rejects an enabled ordinary lead when every profile is unavailable", () => {
  expect(() =>
    decodeDailyCoachingDashboardState({
      archive: [],
      connections: [
        {
          canonicalUrl: "https://lichess.org/@/PlayerOne",
          provider: "lichess",
          status: "profileUnavailable",
          username: "PlayerOne",
        },
      ],
      enabled: true,
      hostConnections: [],
      kind: "connected",
      lead: { kind: "preparingFirstDigest" },
      timezone: "UTC",
    }),
  ).toThrow(/must be profileUnavailable exactly when/)
})

test("round-trips host-connection state and rejects a duplicated host", () => {
  expect(
    decodeDailyCoachingDashboardState({
      archive: [],
      hostConnections: [{ host: "claude" }],
      kind: "notConnected",
    }),
  ).toEqual({
    archive: [],
    hostConnections: [{ host: "claude" }],
    kind: "notConnected",
  })
  expect(() =>
    decodeDailyCoachingDashboardState({
      archive: [],
      hostConnections: [{ host: "claude" }, { host: "claude" }],
      kind: "notConnected",
    }),
  ).toThrow(/must contain unique values/)
})

test("decodes a bounded newest-first Imported Games page", () => {
  expect(() =>
    decodeImportedGameListPage({
      games: [
        {
          endedAt: "2026-08-12T10:00:00.000Z",
          gameImportId: "game-import:fixture:newest",
          learningPathCount: 1,
          opening: null,
          opponentName: null,
          outcome: null,
          provider: "pastedPgn",
          reviewSide: "both",
          timeControlClass: null,
          timeControlRaw: null,
        },
      ],
      nextCursor: null,
    }),
  ).not.toThrow()
  expect(() =>
    decodeImportedGameListPage({
      games: [],
      nextCursor: "cursor-without-a-full-page",
    }),
  ).toThrow(/full page/)
})

test("decodes reviewed-Game coverage and rejects contradictory digest identity", () => {
  const result = {
    coverage: {
      earliestPlayedAt: "2026-08-12T10:00:00.000Z",
      latestPlayedAt: "2026-08-12T10:00:00.000Z",
      reviewedGameCount: 1,
    },
    games: [
      {
        digested: false,
        endedAt: "2026-08-12T10:00:00.000Z",
        gameImportId: "game-import:fixture:reviewed-search",
        imported: true,
        learningPathCount: 0,
        learningTrackKeys: [],
        opening: null,
        opponentName: null,
        opponentRating: null,
        outcome: null,
        provider: "pastedPgn",
        reviewSide: "both",
        reviewedGameKey: "reviewed-game-fixture",
        timeControlClass: null,
      },
    ],
    truncation: { kind: "complete", totalMatchCount: 1 },
  }
  expect(() => decodeReviewedGameSearchResult(result)).not.toThrow()
  expect(() =>
    decodeReviewedGameSearchResult({
      ...result,
      games: [{ ...result.games[0], digestId: null }],
    }),
  ).toThrow(/digest identity/)
  expect(() =>
    decodeReviewedGameSearchResult({
      coverage: { reviewedGameCount: 0, earliestPlayedAt: null },
      games: [],
      truncation: { kind: "complete", totalMatchCount: 0 },
    }),
  ).toThrow(/omit played-time bounds/)
  const { endedAt: _endedAt, ...recordOnlyGame } = result.games[0]
  expect(() =>
    decodeReviewedGameSearchResult({
      coverage: { reviewedGameCount: 1 },
      games: [recordOnlyGame],
      truncation: { kind: "complete", totalMatchCount: 1 },
    }),
  ).not.toThrow()
})

test("decodes canonical contract fixtures", async () => {
  await expect(decodeReviewSessionCoreContract(coreContract)).resolves.toEqual(
    coreContract,
  )
  await expect(decodeImportedGame(importedGame)).resolves.toEqual(importedGame)
  await expect(decodePositionSnapshot(positionSnapshot)).resolves.toEqual(
    positionSnapshot,
  )
  await expect(
    decodeReviewSessionEvidencePacket(evidencePacket),
  ).resolves.toEqual(evidencePacket)
  await expect(decodeEvidenceEntry(evidencePacket.entries[0])).resolves.toEqual(
    evidencePacket.entries[0],
  )
  await expect(
    decodeReviewSessionCommandEnvelope(commands[0]),
  ).resolves.toEqual(commands[0])
  for (const event of events) {
    await expect(decodeReviewSessionEventEnvelope(event)).resolves.toEqual(
      event,
    )
  }
})

test("canonical Decision Explanation carries a Candidate Generation Proof", async () => {
  for (const event of events) {
    const decoded = await decodeReviewSessionEventEnvelope(event)
    if (
      decoded.event.kind !== "completed" ||
      decoded.event.result.kind !== "reviewMomentExplanationRead"
    ) {
      continue
    }
    const path = decoded.event.result.explanation.selectedPaths[0]
    if (!path) {
      throw new Error("canonical Decision Explanation must select a path")
    }
    const proof = path.candidateGenerationProof
    if (!proof) {
      throw new Error(
        "canonical Decision Explanation must prove candidate generation",
      )
    }
    expect(proof.suggestedCandidateRef).toBe(path.candidateRef)
    if (proof.positionGoal.kind !== "gainMaterial") {
      throw new Error("canonical Position Goal must gain material")
    }
    expect(proof.positionGoal.targets).not.toHaveLength(0)
    return
  }
  throw new Error("canonical events must include a Decision Explanation read")
})

test("decodes catalog Opening Identification provenance", async () => {
  const catalogIdentified = {
    ...importedGame,
    game: {
      ...importedGame.game,
      opening: {
        eco: "C92",
        kind: "present",
        name: "Ruy Lopez: Closed",
        provenance: {
          catalogVersion: "chess-openings/2026.04.16",
          kind: "catalog",
          matchedPly: 17,
        },
      },
    },
  }
  await expect(decodeImportedGame(catalogIdentified)).resolves.toEqual(
    catalogIdentified,
  )

  const missingMatchedPly = {
    ...catalogIdentified,
    game: {
      ...catalogIdentified.game,
      opening: {
        ...catalogIdentified.game.opening,
        provenance: {
          catalogVersion: "chess-openings/2026.04.16",
          kind: "catalog",
        },
      },
    },
  }
  await expect(decodeImportedGame(missingMatchedPly)).rejects.toThrow(
    /matches 0 union variants/,
  )
})

test("requires an explicit nullable learning-path vote", async () => {
  const clearVote = {
    ...commands[3],
    command: {
      kind: "updateLearningPathVote",
      learningPathRef: "learning-path:fixture:1",
      gameImportId: "game-import:fixture:1",
      vote: null,
    },
  }
  await expect(decodeReviewSessionCommandEnvelope(clearVote)).resolves.toEqual(
    clearVote,
  )
  await expect(
    decodeReviewSessionCommandEnvelope({
      ...clearVote,
      command: {
        kind: "updateLearningPathVote",
        learningPathRef: "learning-path:fixture:1",
        gameImportId: "game-import:fixture:1",
      },
    }),
  ).rejects.toBeInstanceOf(ContractDecodeError)
})

const presentation = {
  animation: null,
  eloRating: 1246,
  evaluationTimeline: [
    {
      evaluation: { kind: "centipawns", perspective: "white", value: 0 },
      ply: 1,
    },
  ],
  handoffState: "ready",
  maxPly: 1,
  moments: [
    {
      arrows: [],
      authoringReadiness: "prepared",
      bestEvaluation: { label: "Roughly balanced", score: "0.0" },
      board: {
        announcement: "Position after 1. e4. black to move.",
        checkSquare: null,
        lastMove: { from: "e2", to: "e4" },
        pieces: [
          {
            piece: { color: "white", role: "king" },
            pieceId: "white:king:e1",
            square: "e1",
          },
        ],
        positionRef: `sha256:${"0".repeat(64)}`,
      },
      glyph: "!",
      handoff: {
        momentId: "review-moment:fixture:1",
        ply: 1,
        idempotencyKey: "idempotency-key:fixture:presentation",
        selection: {
          criticalMomentId: "review-moment:fixture:1",
          kind: "pipelineCriticalMoment",
        },
        gameImportId: "game-import:fixture:1",
      },
      decisionLearningOutcome: {
        kind: "abstained",
        reason: "noProofValidConcept",
      },
      kind: "automatic",
      learningMaterial: {
        resourceCatalogVersion: "learning-resources/2026-08-03",
        selectionPolicyVersion: "learning-plan-selection/v1",
        tracks: [],
      },
      momentId: "review-moment:fixture:1",
      moveLabel: "1. e4",
      playedEvaluation: { label: "Roughly balanced", score: "0.0" },
      ply: 1,
      summary: "A stable opening move.",
      title: "Positive Highlight",
      tone: "positive",
    },
  ],
  opening: { kind: "absent" },
  orientation: "white",
  presentationRevision: 1,
  reviewSide: "white",
  selectedMomentId: "review-moment:fixture:1",
  gameImportId: "game-import:fixture:1",
  sessionRevision: 1,
  source: "lichess",
  version: "v1",
}

test("decodes complete presentation contracts and rejects semantic gaps", () => {
  expect(decodeReviewSessionPresentation(presentation)).toEqual(presentation)
  expect(() =>
    decodeReviewSessionPresentation({
      ...presentation,
      selectedMomentId: "review-moment:missing:1",
    }),
  ).toThrow(/selectedMomentId/)
  expect(() =>
    decodeReviewSessionPresentation({
      ...presentation,
      moments: [
        {
          ...presentation.moments[0],
          handoff: {
            ...presentation.moments[0]!.handoff,
            ply: 2,
          },
        },
      ],
    }),
  ).toThrow(/handoff/)
})

const gameReviewSnapshot = {
  eloRating: 1246,
  evaluationTimeline: presentation.evaluationTimeline,
  gameImportId: "game-import:fixture:1",
  maxPly: 1,
  moments: [
    {
      arrows: presentation.moments[0]!.arrows,
      bestEvaluation: presentation.moments[0]!.bestEvaluation,
      board: presentation.moments[0]!.board,
      decisionLearningOutcome: presentation.moments[0]!.decisionLearningOutcome,
      glyph: "!",
      index: 0,
      kind: "automatic",
      learningMaterial: presentation.moments[0]!.learningMaterial,
      momentId: "review-moment:fixture:1",
      moveLabel: "1. e4",
      playedEvaluation: presentation.moments[0]!.playedEvaluation,
      ply: 1,
      selection: {
        criticalMomentId: "review-moment:fixture:1",
        kind: "pipelineCriticalMoment",
      },
      sequenceKinds: ["engineBest"],
      summary: "A stable opening move.",
      title: "Positive Highlight",
      tone: "positive",
    },
  ],
  opening: { kind: "absent" },
  orientation: "white",
  reviewSide: "white",
  source: "lichess",
  version: "v1",
}

test("decodes an addressable snapshot and rejects unsteppable moment sets", () => {
  expect(decodeGameReviewSnapshot(gameReviewSnapshot)).toEqual(
    gameReviewSnapshot,
  )
  // Stepping to the next Critical Moment is an index step, so a gap makes
  // "next" mean some other moment.
  expect(() =>
    decodeGameReviewSnapshot({
      ...gameReviewSnapshot,
      moments: [{ ...gameReviewSnapshot.moments[0], index: 1 }],
    }),
  ).toThrow(/index/)
  expect(() =>
    decodeGameReviewSnapshot({
      ...gameReviewSnapshot,
      moments: [
        gameReviewSnapshot.moments[0],
        { ...gameReviewSnapshot.moments[0], index: 1 },
      ],
    }),
  ).toThrow(/moments/)
  expect(() =>
    decodeGameReviewSnapshot({
      ...gameReviewSnapshot,
      maxPly: 0,
    }),
  ).toThrow(/maxPly/)
  expect(() =>
    decodeGameReviewSnapshot({
      ...gameReviewSnapshot,
      moments: [
        {
          ...gameReviewSnapshot.moments[0],
          selection: {
            criticalMomentId: "review-moment:other:1",
            kind: "pipelineCriticalMoment",
          },
        },
      ],
    }),
  ).toThrow(/selection/)
  // A moment offers at most one continuation of each kind, so a repeated kind
  // would give the selector two buttons addressing one line.
  expect(() =>
    decodeGameReviewSnapshot({
      ...gameReviewSnapshot,
      moments: [
        {
          ...gameReviewSnapshot.moments[0],
          sequenceKinds: ["engineBest", "engineBest"],
        },
      ],
    }),
  ).toThrow(/sequenceKinds/)
})

/**
 * The moment's own address is where a continuation's moves are read, so this is
 * the contract that still counts them. The selector snapshot names kinds only.
 */
test("decodes one Review Moment's continuations and counts their moves", () => {
  const reviewMomentSnapshot = {
    gameImportId: "game-import:fixture:1",
    orientation: "white",
    ply: 1,
    reviewMomentId: "review-moment:fixture:1",
    sequences: [
      {
        kind: "engineBest",
        moveCount: 2,
        san: ["e5", "Nf3"],
        title: "Engine continuation",
      },
    ],
    version: "v1",
  }

  expect(decodeReviewMomentSnapshot(reviewMomentSnapshot)).toEqual(
    reviewMomentSnapshot,
  )
  expect(() =>
    decodeReviewMomentSnapshot({
      ...reviewMomentSnapshot,
      sequences: [{ ...reviewMomentSnapshot.sequences[0], moveCount: 3 }],
    }),
  ).toThrow(/moveCount/)
  expect(() =>
    decodeReviewMomentSnapshot({
      ...reviewMomentSnapshot,
      sequences: [
        reviewMomentSnapshot.sequences[0],
        reviewMomentSnapshot.sequences[0],
      ],
    }),
  ).toThrow(/sequences/)
})

test("decodes one exact bounded presentation addition", () => {
  const addition = {
    animation: null,
    changedFields: ["animation", "moment", "selectedMomentId"],
    changedMomentIds: [presentation.moments[0]!.momentId],
    fullRefreshRequired: false,
    moment: presentation.moments[0],
    priorRevision: 1,
    resultingRevision: 2,
    gameImportId: presentation.gameImportId,
    version: "v1",
  }
  expect(decodeReviewSessionPresentationAddition(addition)).toEqual(addition)
  expect(() =>
    decodeReviewSessionPresentationAddition({
      ...addition,
      gameImportId: "game-import:other",
    }),
  ).toThrow(/handoff/)
})

test("validates bounded server-authored animation frames and stable identities", () => {
  const animated = {
    ...presentation,
    animation: {
      frames: [
        {
          durationMs: 600,
          index: 0,
          motions: [{ from: "e1", pieceId: "white:king:e1", to: "e2" }],
          moveLabel: "Ke2",
          placements: [
            {
              piece: { color: "white", role: "king" },
              pieceId: "white:king:e1",
              square: "e2",
            },
          ],
          removedPieceIds: [],
        },
      ],
      lineId: "line:fixture:1",
      reviewMomentId: presentation.moments[0]!.momentId,
      version: "v1",
    },
  }
  expect(decodeReviewSessionPresentation(animated)).toEqual(animated)
  expect(() =>
    decodeReviewSessionPresentation({
      ...animated,
      animation: {
        ...animated.animation,
        frames: [
          {
            ...animated.animation.frames[0],
            motions: [],
          },
        ],
      },
    }),
  ).toThrow(/every and only changed stable-piece squares/)
  expect(() =>
    decodeReviewSessionPresentation({
      ...animated,
      animation: {
        ...animated.animation,
        frames: Array.from({ length: 9 }, (_, index) => ({
          ...animated.animation.frames[0],
          index,
          motions: [],
          placements: presentation.moments[0]!.board.pieces,
        })),
      },
    }),
  ).toThrow(/one and eight bounded frames/)
})

const moveSequencePresentation = {
  kind: "engineBest",
  moves: [
    {
      board: {
        announcement: "Move 1 of 1: e4.",
        checkSquare: null,
        lastMove: { from: "e2", to: "e4" },
        pieces: [
          {
            piece: { color: "white", role: "king" },
            pieceId: "white:king:e1",
            square: "e1",
          },
        ],
      },
      index: 1,
      san: "e4",
    },
  ],
  orientation: "white",
  reviewMomentId: "review-moment:fixture:1",
  sequenceRef: "move-sequence:fixture:1",
  gameImportId: "game-import:fixture:1",
  title: "Engine continuation",
  version: "v1",
}

test("decodes non-empty canonical move sequences and rejects malformed navigation facts", () => {
  expect(decodeMoveSequencePresentation(moveSequencePresentation)).toEqual(
    moveSequencePresentation,
  )
  const longMoveSequencePresentation = {
    ...moveSequencePresentation,
    moves: Array.from({ length: 17 }, (_, index) => ({
      ...moveSequencePresentation.moves[0],
      index: index + 1,
    })),
  }
  expect(decodeMoveSequencePresentation(longMoveSequencePresentation)).toEqual(
    longMoveSequencePresentation,
  )
  expect(() =>
    decodeMoveSequencePresentation({
      ...moveSequencePresentation,
      moves: [],
    }),
  ).toThrow(/at least one canonical move/)
  expect(() =>
    decodeMoveSequencePresentation({
      ...moveSequencePresentation,
      moves: [{ ...moveSequencePresentation.moves[0], index: 0 }],
    }),
  ).toThrow(/contiguous and one-based/)
  expect(() =>
    decodeMoveSequencePresentation({
      ...moveSequencePresentation,
      moves: [
        {
          ...moveSequencePresentation.moves[0],
          board: {
            ...moveSequencePresentation.moves[0]!.board,
            lastMove: { from: "e4", to: "e4" },
          },
        },
      ],
    }),
  ).toThrow(/distinct squares/)
})

test("generated rate-limit outcome stays rateLimited plus retryAfter", async () => {
  const limited = events.find(
    (event) =>
      event.event.kind === "unavailable" &&
      event.event.reason.kind === "rateLimited",
  )
  if (!limited) {
    throw new Error("canonical events must include a rate-limited outcome")
  }
  const decoded = await decodeReviewSessionEventEnvelope(limited)
  expect(decoded.event).toMatchObject({
    kind: "unavailable",
    reason: { kind: "rateLimited", retryAfterSeconds: 60 },
    retry: { kind: "retryAfter", seconds: 60 },
  })
})
