//! The RSA key pair the tests sign and verify tokens with.
//!
//! Generated by `bun run keys:test` rather than checked in. A committed file
//! opening with a PEM private-key header is a supported secret-scanning
//! pattern, and push protection refuses it whatever a README calls the key.
//! Nothing here needs one particular key, only a real one, so the honest fix
//! is to make one. `chenchess-rust#test` depends on the generating task, so a
//! fresh clone makes the pair before the suite reads it.

use std::{path::PathBuf, sync::OnceLock};

static PRIVATE_KEY: OnceLock<String> = OnceLock::new();
static JWKS: OnceLock<String> = OnceLock::new();

/// The PKCS#8 private key, for `EncodingKey::from_rsa_pem`.
pub(crate) fn private_key_pem() -> &'static str {
    PRIVATE_KEY.get_or_init(|| read("auth-private-key.pem"))
}

/// Its public half as a JWKS, with `kid` `firebase-test-key`.
pub(crate) fn jwks() -> &'static str {
    JWKS.get_or_init(|| read("auth-jwks.json"))
}

fn read(name: &str) -> String {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("certification-fixtures")
        .join(name);
    std::fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "{}: {error}. Run `bun run keys:test` to generate the Coach Engine test keys.",
            path.display()
        )
    })
}
