use crate::review_session_contract::CurriculumLearningConcept;

use super::resources::*;

#[derive(Debug, Clone, Copy)]
pub(super) struct PracticeResource {
    pub(super) id: &'static str,
    pub(super) title: &'static str,
    pub(super) path: &'static str,
}

#[derive(Debug, Clone, Copy)]
pub(super) struct CurriculumEntry {
    pub(super) concept: CurriculumLearningConcept,
    pub(super) title: &'static str,
    pub(super) puzzle_theme: Option<&'static str>,
    pub(super) practice: &'static [PracticeResource],
}

macro_rules! entry {
    ($concept:ident, $title:literal, $theme:expr, $practice:expr) => {
        CurriculumEntry {
            concept: CurriculumLearningConcept::$concept,
            title: $title,
            puzzle_theme: $theme,
            practice: $practice,
        }
    };
}

#[rustfmt::skip]
pub(super) const CURRICULUM: &[CurriculumEntry] = &[
    entry!(PieceCheckmates, "Piece checkmates", None, PIECE_CHECKMATE_PRACTICE),
    entry!(CheckmatePatterns, "Checkmate patterns", None, CHECKMATE_PATTERN_PRACTICE),
    entry!(KnightAndBishopMate, "Knight and bishop mate", None, KNIGHT_BISHOP_MATE_PRACTICE),
    entry!(Pin, "Pin", Some("pin"), PIN_PRACTICE),
    entry!(Skewer, "Skewer", Some("skewer"), SKEWER_PRACTICE),
    entry!(Fork, "Fork", Some("fork"), FORK_PRACTICE),
    entry!(HangingPiece, "Hanging piece", Some("hangingPiece"), NO_PRACTICE),
    entry!(DiscoveredAttack, "Discovered attack", Some("discoveredAttack"), DISCOVERED_ATTACK_PRACTICE),
    entry!(DoubleCheck, "Double check", Some("doubleCheck"), DOUBLE_CHECK_PRACTICE),
    entry!(OverloadedPiece, "Overloaded piece", None, OVERLOADED_PIECE_PRACTICE),
    entry!(Intermezzo, "Intermezzo", Some("intermezzo"), INTERMEZZO_PRACTICE),
    entry!(XRayAttack, "X-ray attack", Some("xRayAttack"), X_RAY_PRACTICE),
    entry!(Zugzwang, "Zugzwang", Some("zugzwang"), ZUGZWANG_PRACTICE),
    entry!(Interference, "Interference", Some("interference"), INTERFERENCE_PRACTICE),
    entry!(GreekGift, "Greek gift", None, GREEK_GIFT_PRACTICE),
    entry!(Deflection, "Deflection", Some("deflection"), DEFLECTION_PRACTICE),
    entry!(Attraction, "Attraction", Some("attraction"), ATTRACTION_PRACTICE),
    entry!(Underpromotion, "Underpromotion", Some("underPromotion"), UNDERPROMOTION_PRACTICE),
    entry!(Desperado, "Desperado", None, DESPERADO_PRACTICE),
    entry!(CounterCheck, "Counter check", None, COUNTER_CHECK_PRACTICE),
    entry!(CapturingDefender, "Capture the defender", Some("capturingDefender"), CAPTURING_DEFENDER_PRACTICE),
    entry!(Clearance, "Clearance", Some("clearance"), CLEARANCE_PRACTICE),
    entry!(KeySquares, "Key squares", None, KEY_SQUARES_PRACTICE),
    entry!(Opposition, "Opposition", None, OPPOSITION_PRACTICE),
    entry!(SeventhRankRookPawn, "Seventh-rank rook pawn", None, SEVENTH_RANK_ROOK_PAWN_PRACTICE),
    entry!(PassiveRookDefense, "Passive rook defense", None, PASSIVE_ROOK_PRACTICE),
    entry!(Lucena, "Lucena position", None, BASIC_ROOK_ENDGAME_PRACTICE),
    entry!(Philidor, "Philidor position", None, BASIC_ROOK_ENDGAME_PRACTICE),
    entry!(IntermediateRookEndings, "Intermediate rook endings", None, INTERMEDIATE_ROOK_PRACTICE),
    entry!(PracticalRookEndings, "Practical rook endings", None, PRACTICAL_ROOK_PRACTICE),
    entry!(AdvancedPawn, "Advanced pawn", Some("advancedPawn"), NO_PRACTICE),
    entry!(AttackingF2F7, "Attacking f2 or f7", Some("attackingF2F7"), NO_PRACTICE),
    entry!(ExposedKing, "Exposed king", Some("exposedKing"), NO_PRACTICE),
    entry!(KingsideAttack, "Kingside attack", Some("kingsideAttack"), NO_PRACTICE),
    entry!(QueensideAttack, "Queenside attack", Some("queensideAttack"), NO_PRACTICE),
    entry!(Sacrifice, "Sacrifice", Some("sacrifice"), NO_PRACTICE),
    entry!(TrappedPiece, "Trapped piece", Some("trappedPiece"), NO_PRACTICE),
    entry!(CollinearMove, "Collinear move", Some("collinearMove"), NO_PRACTICE),
    entry!(DiscoveredCheck, "Discovered check", Some("discoveredCheck"), DISCOVERED_ATTACK_PRACTICE),
    entry!(DefensiveMove, "Defensive move", Some("defensiveMove"), NO_PRACTICE),
    entry!(QuietMove, "Quiet move", Some("quietMove"), NO_PRACTICE),
    entry!(AnastasiaMate, "Anastasia's mate", Some("anastasiaMate"), NO_PRACTICE),
    entry!(ArabianMate, "Arabian mate", Some("arabianMate"), NO_PRACTICE),
    entry!(BackRankMate, "Back-rank mate", Some("backRankMate"), NO_PRACTICE),
    entry!(BalestraMate, "Balestra mate", Some("balestraMate"), NO_PRACTICE),
    entry!(BlindSwineMate, "Blind swine mate", Some("blindSwineMate"), NO_PRACTICE),
    entry!(BodenMate, "Boden's mate", Some("bodenMate"), NO_PRACTICE),
    entry!(CornerMate, "Corner mate", Some("cornerMate"), NO_PRACTICE),
    entry!(DoubleBishopMate, "Double bishop mate", Some("doubleBishopMate"), NO_PRACTICE),
    entry!(DovetailMate, "Dovetail mate", Some("dovetailMate"), NO_PRACTICE),
    entry!(EpauletteMate, "Epaulette mate", Some("epauletteMate"), NO_PRACTICE),
    entry!(HookMate, "Hook mate", Some("hookMate"), NO_PRACTICE),
    entry!(KillBoxMate, "Kill box mate", Some("killBoxMate"), NO_PRACTICE),
    entry!(PillsburysMate, "Pillsbury's mate", Some("pillsburysMate"), NO_PRACTICE),
    entry!(MorphysMate, "Morphy's mate", Some("morphysMate"), NO_PRACTICE),
    entry!(OperaMate, "Opera mate", Some("operaMate"), NO_PRACTICE),
    entry!(SwallowstailMate, "Swallow's-tail mate", Some("swallowstailMate"), NO_PRACTICE),
    entry!(TriangleMate, "Triangle mate", Some("triangleMate"), NO_PRACTICE),
    entry!(VukovicMate, "Vuković mate", Some("vukovicMate"), NO_PRACTICE),
    entry!(SmotheredMate, "Smothered mate", Some("smotheredMate"), NO_PRACTICE),
    entry!(Castling, "Castling", Some("castling"), NO_PRACTICE),
    entry!(EnPassant, "En passant", Some("enPassant"), NO_PRACTICE),
    entry!(Promotion, "Promotion", Some("promotion"), NO_PRACTICE),
    entry!(RookEndgame, "Rook endgame", Some("rookEndgame"), NO_PRACTICE),
    entry!(BishopEndgame, "Bishop endgame", Some("bishopEndgame"), NO_PRACTICE),
    entry!(PawnEndgame, "Pawn endgame", Some("pawnEndgame"), NO_PRACTICE),
    entry!(KnightEndgame, "Knight endgame", Some("knightEndgame"), NO_PRACTICE),
    entry!(QueenEndgame, "Queen endgame", Some("queenEndgame"), NO_PRACTICE),
    entry!(QueenAndRookEndgame, "Queen and rook endgame", Some("queenRookEndgame"), NO_PRACTICE),
    entry!(Equality, "Drawing resource", Some("equality"), NO_PRACTICE),
    entry!(Advantage, "Advantage", Some("advantage"), NO_PRACTICE),
    entry!(CrushingAdvantage, "Crushing advantage", Some("crushing"), NO_PRACTICE),
    entry!(Checkmate, "Checkmate", Some("mate"), NO_PRACTICE),
];

#[cfg(test)]
pub(super) const NON_CONCEPT_PUZZLE_THEMES: &[&str] = &[
    "mix",
    "opening",
    "middlegame",
    "endgame",
    "mateIn1",
    "mateIn2",
    "mateIn3",
    "mateIn4",
    "mateIn5",
    "oneMove",
    "short",
    "long",
    "veryLong",
    "master",
    "masterVsMaster",
    "superGM",
];

#[cfg(test)]
pub(super) const PINNED_VISIBLE_PUZZLE_THEMES: &[&str] = &[
    "mix",
    "advancedPawn",
    "advantage",
    "anastasiaMate",
    "arabianMate",
    "attackingF2F7",
    "attraction",
    "backRankMate",
    "balestraMate",
    "blindSwineMate",
    "triangleMate",
    "bishopEndgame",
    "bodenMate",
    "capturingDefender",
    "collinearMove",
    "castling",
    "clearance",
    "cornerMate",
    "crushing",
    "defensiveMove",
    "deflection",
    "discoveredAttack",
    "discoveredCheck",
    "doubleBishopMate",
    "doubleCheck",
    "dovetailMate",
    "equality",
    "endgame",
    "epauletteMate",
    "enPassant",
    "exposedKing",
    "fork",
    "hangingPiece",
    "hookMate",
    "interference",
    "intermezzo",
    "kingsideAttack",
    "killBoxMate",
    "pillsburysMate",
    "morphysMate",
    "vukovicMate",
    "knightEndgame",
    "long",
    "master",
    "masterVsMaster",
    "mate",
    "mateIn1",
    "mateIn2",
    "mateIn3",
    "mateIn4",
    "mateIn5",
    "smotheredMate",
    "middlegame",
    "oneMove",
    "opening",
    "operaMate",
    "pawnEndgame",
    "pin",
    "promotion",
    "queenEndgame",
    "queenRookEndgame",
    "queensideAttack",
    "quietMove",
    "rookEndgame",
    "sacrifice",
    "short",
    "superGM",
    "swallowstailMate",
    "trappedPiece",
    "skewer",
    "underPromotion",
    "veryLong",
    "xRayAttack",
    "zugzwang",
];

#[cfg(test)]
pub(super) const PINNED_PRACTICE_IDS: &[&str] = &[
    "BJy6fEDf", "fE4k21MW", "8yadFPpU", "PDkQDt6u", "96Lij7wH", "Rg2cMBZ6", "ByhlXnmM", "9ogFv8Ac",
    "tuoBxVE5", "Qj281y1p", "MnsJEWnI", "RUQASaZm", "o734CNqp", "ITWY4GN2", "lyVYjhPG", "9cKgYrHb",
    "g1fxVZu9", "s5pLU7Of", "kdKpaYLW", "jOZejFWk", "49fDW0wP", "0YcGiH4Y", "CgjKPvxQ", "udx042D6",
    "Grmtwuft", "xebrDvFe", "A4ujYOer", "pt20yRkT", "MkDViieT", "pqUSUw8Y", "heQDnvq7", "wS23j5Tm",
];

pub(super) fn entry_for(concept: CurriculumLearningConcept) -> Option<&'static CurriculumEntry> {
    CURRICULUM.iter().find(|entry| entry.concept == concept)
}
