// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineEvaluation } from "./EngineEvaluation.js";
import type { EvaluationLoss } from "./EvaluationLoss.js";

export type AlternativeMoveEvaluation = { selectedMove: EngineEvaluation, bestMoveUci: string, bestMove: EngineEvaluation, comparison: EvaluationLoss, };
