// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlternativeMoveEvaluation } from "./AlternativeMoveEvaluation.js";
import type { AlternativeMoveId } from "./AlternativeMoveId.js";
import type { BranchParent } from "./BranchParent.js";
import type { BranchRef } from "./BranchRef.js";
import type { PositionRef } from "./PositionRef.js";
import type { PositionSnapshot } from "./PositionSnapshot.js";
import type { StrongestReply } from "./StrongestReply.js";

export type AlternativeMoveResult = { alternativeMoveId: AlternativeMoveId, branchRef: BranchRef, parent: BranchParent, sourcePositionRef: PositionRef, moveUci: string, resultingPosition: PositionSnapshot, evaluation: AlternativeMoveEvaluation, strongestReply: StrongestReply, };
