// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceId } from "./EvidenceId.js";

export type AlternativeMoveAssessmentEvidenceRefs = { targetBranch: EvidenceId, sourceEngine: EvidenceId, resultingEngine: EvidenceId, sourceHuman: EvidenceId, resultingHuman: EvidenceId, };
