// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlternativeMoveId } from "./AlternativeMoveId.js";
import type { AssessmentDimension } from "./AssessmentDimension.js";
import type { CoachTurnId } from "./CoachTurnId.js";

export type AlternativeMoveAssessment = { coachTurnId: CoachTurnId, alternativeMoveId: AlternativeMoveId, objectiveQuality: AssessmentDimension, findability: AssessmentDimension, resilience: AssessmentDimension, };
