// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomicChessFactData } from "./AtomicChessFactData.js";
import type { AtomicFactRef } from "./AtomicFactRef.js";

export type AtomicChessFact = { factRef: AtomicFactRef, data: AtomicChessFactData, };
