// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchParent } from "./BranchParent.js";
import type { BranchRef } from "./BranchRef.js";
import type { PositionRef } from "./PositionRef.js";

export type BranchEvidence = { branchRef: BranchRef, parent: BranchParent, sourcePositionRef: PositionRef, moveUci: string, resultingPositionRef: PositionRef, };
