// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchRef } from "./BranchRef.js";
import type { PositionRef } from "./PositionRef.js";

export type BranchParent = { "kind": "root", positionRef: PositionRef, } | { "kind": "move", branchRef: BranchRef, };
