// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineCandidateEvidence } from "./EngineCandidateEvidence.js";
import type { PlayerMoveEvidence } from "./PlayerMoveEvidence.js";
import type { RankedAlternativeEvidence } from "./RankedAlternativeEvidence.js";

export type CandidateEvidence = { "kind": "singlePv", authoritative: EngineCandidateEvidence, playerMove: PlayerMoveEvidence, } | { "kind": "multiPv", authoritativeSinglePv: EngineCandidateEvidence, requestedCount: number, 
/**
 * Ranks two and up only. Rank one **is** `authoritative_single_pv`, so
 * it is absent here rather than restated — a MultiPV rank-one score is
 * a second, noisier reading of a position the SinglePV search already
 * scored, and the two disagree (ADR 0041).
 */
rankedAlternatives: Array<RankedAlternativeEvidence>, playerMove: PlayerMoveEvidence, };
