// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomicFactRef } from "./AtomicFactRef.js";
import type { DecisionCandidateRef } from "./DecisionCandidateRef.js";
import type { KnowledgeNodeRef } from "./KnowledgeNodeRef.js";
import type { PositionGoal } from "./PositionGoal.js";

export type CandidateGenerationProof = { supportingFactRefs: Array<AtomicFactRef>, conceptNodeRef: KnowledgeNodeRef, positionGoal: PositionGoal, suggestedCandidateRef: DecisionCandidateRef, };
