// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far an alternative fell short of the best move, measured inside one
 * MultiPV search.
 */
export type CandidateGap = { "kind": "centipawns", behindBest: number, } | { "kind": "slowerMate", extraPlies: number, } | { "kind": "missesForcedMate" } | { "kind": "concedesForcedMate" } | { "kind": "incommensurable" };
