// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanonicalGameMove } from "./CanonicalGameMove.js";
import type { CompletedGameOutcome } from "./CompletedGameOutcome.js";
import type { GameRef } from "./GameRef.js";
import type { MetadataText } from "./MetadataText.js";
import type { OpeningMetadata } from "./OpeningMetadata.js";
import type { PlayerMetadata } from "./PlayerMetadata.js";
import type { PositionRef } from "./PositionRef.js";

export type CanonicalCompletedGame = { gameRef: GameRef, white: PlayerMetadata, black: PlayerMetadata, event: MetadataText, site: MetadataText, opening: OpeningMetadata, outcome: CompletedGameOutcome, moves: Array<CanonicalGameMove>, finalPositionRef: PositionRef, };
