// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { PositionRef } from "./PositionRef.js";

export type CanonicalGameMove = { ply: number, moveNumber: number, side: Color, san: string, uci: string, beforePositionRef: PositionRef, afterPositionRef: PositionRef, };
