// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyCoachingMutationRejectionReason } from "./DailyCoachingMutationRejectionReason.js";
import type { DailyCoachingProvider } from "./DailyCoachingProvider.js";
import type { DailyCoachingUnavailableReason } from "./DailyCoachingUnavailableReason.js";
import type { RetryDirective } from "./RetryDirective.js";

export type CheckPlayingProfileOutcome = { "outcome": "reachable", provider: DailyCoachingProvider, } | { "outcome": "profileUnavailable", provider: DailyCoachingProvider, } | { "outcome": "providerUnavailable", provider: DailyCoachingProvider, retry: RetryDirective, } | { "outcome": "rejected", reason: DailyCoachingMutationRejectionReason, } | { "outcome": "unavailable", reason: DailyCoachingUnavailableReason, retry: RetryDirective, };
