// @generated by generate_review_session_contract; do not edit.

// Every Chess.com shared Game URL form ChenChess imports, anchored.
// Looser than the Engine on Game id range: the Engine stays the authority and
// rejects what this admits with a typed reason.
export const CHESS_COM_GAME_URL_PATTERN = "^https://www\\.chess\\.com/game/(?:computer|daily|live)/[1-9][0-9]*$";
