// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchRef } from "./BranchRef.js";
import type { CriticalMomentId } from "./CriticalMomentId.js";

export type CoachTurnTarget = { "kind": "importedGameMove", criticalMomentId: CriticalMomentId, ply: number, uci: string, } | { "kind": "alternativeMove", branchRef: BranchRef, uci: string, };
