// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoachTurnId } from "./CoachTurnId.js";
import type { CoachTurnTarget } from "./CoachTurnTarget.js";
import type { EvidenceId } from "./EvidenceId.js";
import type { PositionRef } from "./PositionRef.js";
import type { ReviewedMoveAnchor } from "./ReviewedMoveAnchor.js";

export type CoachTurnContext = { coachTurnId: CoachTurnId, reviewedMove: ReviewedMoveAnchor, selectedPositionRef: PositionRef, target: CoachTurnTarget, requiredEvidenceRefs: Array<EvidenceId>, };
