// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlternativeMoveAssessmentEvidenceRefs } from "./AlternativeMoveAssessmentEvidenceRefs.js";
import type { AlternativeMoveResult } from "./AlternativeMoveResult.js";
import type { CoachTurnContext } from "./CoachTurnContext.js";
import type { CoachTurnId } from "./CoachTurnId.js";
import type { PositionSnapshot } from "./PositionSnapshot.js";
import type { ReviewSessionEvidencePacket } from "./ReviewSessionEvidencePacket.js";

export type CoachTurnFacts = { coachTurnId: CoachTurnId, message: string, context: CoachTurnContext, alternativeMove: AlternativeMoveResult, ancestorBranch: Array<AlternativeMoveResult>, sourcePosition: PositionSnapshot, evidencePacket: ReviewSessionEvidencePacket, evidence: AlternativeMoveAssessmentEvidenceRefs, };
