// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { DecisiveGameTermination } from "./DecisiveGameTermination.js";
import type { DrawGameTermination } from "./DrawGameTermination.js";

export type CompletedGameOutcome = { "kind": "decisive", winner: Color, termination: DecisiveGameTermination, } | { "kind": "draw", termination: DrawGameTermination, };
