// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomicFactRef } from "./AtomicFactRef.js";
import type { DecisionCandidateRef } from "./DecisionCandidateRef.js";
import type { KnowledgeRuleRef } from "./KnowledgeRuleRef.js";
import type { LineStepRef } from "./LineStepRef.js";
import type { SemanticOutcomeRef } from "./SemanticOutcomeRef.js";

export type ConceptValidationProof = { candidateRef: DecisionCandidateRef, causalStepRef: LineStepRef, payoffStepRef: LineStepRef, recognitionRuleRef: KnowledgeRuleRef, supportingFactRefs: Array<AtomicFactRef>, outcomeRefs: Array<SemanticOutcomeRef>, };
