// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectPlayingProfileRejectionReason } from "./ConnectPlayingProfileRejectionReason.js";
import type { DailyCoachingProvider } from "./DailyCoachingProvider.js";
import type { DailyCoachingUnavailableReason } from "./DailyCoachingUnavailableReason.js";
import type { PlayingProfileConnectionStatus } from "./PlayingProfileConnectionStatus.js";
import type { RetryDirective } from "./RetryDirective.js";

export type ConnectPlayingProfileOutcome = { "outcome": "completed", provider: DailyCoachingProvider, username: string, canonicalUrl: string, status: PlayingProfileConnectionStatus, } | { "outcome": "rejected", reason: ConnectPlayingProfileRejectionReason, } | { "outcome": "unavailable", reason: DailyCoachingUnavailableReason, retry: RetryDirective, };
