// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CriticalMomentFactualClaim = "positiveGrade" | "playedMove" | "playedPopularity" | "positiveAchievement" | "positiveDifficulty" | "positiveTakeaway" | "improvementOutcome" | "improvementConsequence" | "improvementCorrection" | "improvementDecisionCue" | "improvementTakeaway" | "neutralReason" | "neutralObservation" | "opponentResource" | "materialVerdict" | "moveTarget";
