// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactDigest } from "./ArtifactDigest.js";
import type { CriticalMomentFactualClaim } from "./CriticalMomentFactualClaim.js";

export type CriticalMomentGroundingLedger = { factsRef: ArtifactDigest, factualClaims: Array<CriticalMomentFactualClaim>, };
