// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CriticalMomentIntentAuthoringInstructions } from "./CriticalMomentIntentAuthoringInstructions.js";
import type { IntentEnrichment } from "./IntentEnrichment.js";

export type CriticalMomentIntentAuthoringContext = { enrichment?: IntentEnrichment | null, instructions: CriticalMomentIntentAuthoringInstructions, };
