// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyCoachingGameCard } from "./DailyCoachingGameCard.js";
import type { DailyCoachingPriority } from "./DailyCoachingPriority.js";

export type DailyCoachingDigestDetail = { digestId: string, coverageDate: string, publishedAt: string, timezone: string, gameCount: number, learningPathCount: number, priorities: Array<DailyCoachingPriority>, games: Array<DailyCoachingGameCard>, };
