// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameImportId } from "./GameImportId.js";
import type { LearningResource } from "./LearningResource.js";
import type { LearningTrackPurpose } from "./LearningTrackPurpose.js";

export type DailyCoachingPriority = { title: string, purpose: LearningTrackPurpose, supportingGameCount: number, supportingGameImportIds: Array<GameImportId>, resources: Array<LearningResource>, };
