// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyCoachingGameOutcome } from "./DailyCoachingGameOutcome.js";
import type { DailyCoachingOpening } from "./DailyCoachingOpening.js";
import type { DailyCoachingProvider } from "./DailyCoachingProvider.js";
import type { DailyCoachingReviewSide } from "./DailyCoachingReviewSide.js";
import type { DailyCoachingTimeControlClass } from "./DailyCoachingTimeControlClass.js";
import type { GameImportId } from "./GameImportId.js";

export type DailyCoachingGameCard = { gameImportId: GameImportId, provider: DailyCoachingProvider, outcome: DailyCoachingGameOutcome, reviewSide: DailyCoachingReviewSide, opening: DailyCoachingOpening | null, opponentName: string | null, endedAt: string, timeControlRaw: string, timeControlClass: DailyCoachingTimeControlClass, learningPathCount: number, };
