// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyCoachingMutationRejectionReason } from "./DailyCoachingMutationRejectionReason.js";
import type { DailyCoachingSetupState } from "./DailyCoachingSetupState.js";
import type { DailyCoachingUnavailableReason } from "./DailyCoachingUnavailableReason.js";
import type { RetryDirective } from "./RetryDirective.js";

export type DailyCoachingMutationOutcome = { "outcome": "completed", state: DailyCoachingSetupState, } | { "outcome": "rejected", reason: DailyCoachingMutationRejectionReason, } | { "outcome": "unavailable", reason: DailyCoachingUnavailableReason, retry: RetryDirective, };
