// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoachingHostConnection } from "./CoachingHostConnection.js";
import type { DailyCoachingDigestSummary } from "./DailyCoachingDigestSummary.js";
import type { DailyCoachingLeadState } from "./DailyCoachingLeadState.js";
import type { PlayingProfileConnection } from "./PlayingProfileConnection.js";

export type DailyCoachingDashboardState = { "kind": "notConnected", archive: Array<DailyCoachingDigestSummary>, hostConnections: Array<CoachingHostConnection>, } | { "kind": "connected", enabled: boolean, digestEmailEnabled?: boolean | null, timezone: string, connections: Array<PlayingProfileConnection>, hostConnections: Array<CoachingHostConnection>, lead: DailyCoachingLeadState, archive: Array<DailyCoachingDigestSummary>, };
