// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DailyCoachingLeadState = { "kind": "disabled" } | { "kind": "profileUnavailable" } | { "kind": "preparingFirstDigest" } | { "kind": "noEligibleGamesYet" } | { "kind": "initialBackfillUnavailable" } | { "kind": "noEligibleGames", coverageDate: string, } | { "kind": "digest", digestId: string, };
