// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayingProfileConnection } from "./PlayingProfileConnection.js";

export type DailyCoachingSetupState = { "kind": "notConnected" } | { "kind": "connected", enabled: boolean, timezone: string, connections: Array<PlayingProfileConnection>, };
