// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomicFactRef } from "./AtomicFactRef.js";
import type { DecisionCandidateOrigin } from "./DecisionCandidateOrigin.js";
import type { DecisionCandidateRef } from "./DecisionCandidateRef.js";
import type { DecisionLineStep } from "./DecisionLineStep.js";
import type { EngineAssessment } from "./EngineAssessment.js";
import type { SemanticOutcome } from "./SemanticOutcome.js";

export type DecisionCandidate = { candidateRef: DecisionCandidateRef, rootMoveUci: string, origins: Array<DecisionCandidateOrigin>, retainedVariation: Array<string>, lineSteps: Array<DecisionLineStep>, factRefs: Array<AtomicFactRef>, outcomes: Array<SemanticOutcome>, assessment: EngineAssessment, };
