// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomicChessFact } from "./AtomicChessFact.js";
import type { CandidateEvidence } from "./CandidateEvidence.js";
import type { ChessKnowledgeGraphVersion } from "./ChessKnowledgeGraphVersion.js";
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { DecisionCandidate } from "./DecisionCandidate.js";
import type { DecisionExplanationGeneration } from "./DecisionExplanationGeneration.js";
import type { DecisionExplanationRef } from "./DecisionExplanationRef.js";
import type { DecisionPositionSnapshot } from "./DecisionPositionSnapshot.js";
import type { ExplanationPath } from "./ExplanationPath.js";
import type { GameRef } from "./GameRef.js";
import type { PositionSnapshot } from "./PositionSnapshot.js";
import type { PreferenceProof } from "./PreferenceProof.js";
import type { ProofCapability } from "./ProofCapability.js";

export type DecisionExplanation = { decisionExplanationRef: DecisionExplanationRef, generation: DecisionExplanationGeneration, knowledgeGraphVersion: ChessKnowledgeGraphVersion, gameRef: GameRef, criticalMomentId: CriticalMomentId, positionSnapshot: PositionSnapshot, 
/**
 * The complete normalized engine input is durable so the transient
 * construction graph, including rejected matches, can be recomputed.
 */
candidateEvidence: CandidateEvidence, snapshots: Array<DecisionPositionSnapshot>, facts: Array<AtomicChessFact>, candidates: Array<DecisionCandidate>, selectedPaths: Array<ExplanationPath>, preference: PreferenceProof | null, capability: ProofCapability, };
