// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionLearningAbstentionReason } from "./DecisionLearningAbstentionReason.js";

export type DecisionLearningOutcome = { "kind": "notAttempted" } | { "kind": "trackSelected" } | { "kind": "explanationUnmapped" } | { "kind": "abstained", reason: DecisionLearningAbstentionReason, };
