// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { DecisionPositionSnapshotRef } from "./DecisionPositionSnapshotRef.js";
import type { LineStepRef } from "./LineStepRef.js";
import type { PieceAtSquare } from "./PieceAtSquare.js";
import type { PieceRole } from "./PieceRole.js";
import type { Square } from "./Square.js";

export type DecisionLineStep = { stepRef: LineStepRef, beforeSnapshotRef: DecisionPositionSnapshotRef, afterSnapshotRef: DecisionPositionSnapshotRef, uci: string, mover: Color, role: PieceRole, fromSquare: Square, toSquare: Square, captured: PieceAtSquare | null, promotion: PieceRole | null, };
