// @generated by generate_review_session_contract; do not edit.

import {
  ContractDecodeError,
  validateContract,
  validateContractDefinition,
} from "./contract-runtime.js"
import { validatePositionSnapshot } from "./position-integrity.js"
import schemaDocument from "./review-session.schema.json"
import type { DailyCoachingDashboardState } from "./DailyCoachingDashboardState.js"
import type { DailyCoachingDigestDetail } from "./DailyCoachingDigestDetail.js"
import type { DailyCoachingDigestSummary } from "./DailyCoachingDigestSummary.js"
import type { EvidenceEntry } from "./EvidenceEntry.js"
import type { GameReviewSnapshot } from "./GameReviewSnapshot.js"
import type { ImportedGame } from "./ImportedGame.js"
import type { ImportedGameListPage } from "./ImportedGameListPage.js"
import type { MoveSequencePresentation } from "./MoveSequencePresentation.js"
import type { MoveSequenceSnapshot } from "./MoveSequenceSnapshot.js"
import type { PositionSnapshot } from "./PositionSnapshot.js"
import type { ReviewMomentSnapshot } from "./ReviewMomentSnapshot.js"
import type { ReviewSessionCommandEnvelope } from "./ReviewSessionCommandEnvelope.js"
import type { ReviewSessionCoreContract } from "./ReviewSessionCoreContract.js"
import type { ReviewSessionEventEnvelope } from "./ReviewSessionEventEnvelope.js"
import type { ReviewSessionEvidencePacket } from "./ReviewSessionEvidencePacket.js"
import type { ReviewSessionPresentation } from "./ReviewSessionPresentation.js"
import type { ReviewSessionPresentationAddition } from "./ReviewSessionPresentationAddition.js"
import type { ReviewedGameSearchResult } from "./ReviewedGameSearchResult.js"

export { ContractDecodeError } from "./contract-runtime.js"

export async function decodeReviewSessionCoreContract(
  value: unknown,
): Promise<ReviewSessionCoreContract> {
  validateContract(schemaDocument, value)
  const core = value as ReviewSessionCoreContract
  await validatePositionSnapshot(core.positionSnapshot)
  await validateEvidencePacket(core.evidencePacket)
  validateCoreEvidenceRefs(core)
  return core
}

export async function decodeReviewSessionCommandEnvelope(
  value: unknown,
): Promise<ReviewSessionCommandEnvelope> {
  return decodeDefinition("ReviewSessionCommandEnvelope", value)
}

export async function decodeReviewSessionEventEnvelope(
  value: unknown,
): Promise<ReviewSessionEventEnvelope> {
  return decodeDefinition("ReviewSessionEventEnvelope", value)
}

export function decodeDailyCoachingDashboardState(
  value: unknown,
): DailyCoachingDashboardState {
  const dashboard = decodeDefinition<DailyCoachingDashboardState>(
    "DailyCoachingDashboardState",
    value,
  )
  dashboard.archive.forEach((summary, index) =>
    validateDailyCoachingDigestSummary(summary, `$.archive[${index}]`),
  )
  requireDescendingPublishedAt(dashboard.archive, "$.archive")
  requireUnique(
    dashboard.hostConnections.map(({ host }) => host),
    "$.hostConnections",
  )
  if (dashboard.kind === "connected") {
    if (dashboard.connections.length === 0) {
      throw new ContractDecodeError(
        "$.connections",
        "must contain at least one connected playing profile",
      )
    }
    requireNonEmpty([dashboard.timezone], "$.timezone")
    const allProfilesUnavailable = dashboard.connections.every(
      (connection) => connection.status === "profileUnavailable",
    )
    if (
      (dashboard.lead.kind === "profileUnavailable") !==
      (dashboard.enabled && allProfilesUnavailable)
    ) {
      throw new ContractDecodeError(
        "$.lead",
        "must be profileUnavailable exactly when coaching is enabled and every profile is unavailable",
      )
    } else if (dashboard.lead.kind === "noEligibleGames") {
      requireDate(dashboard.lead.coverageDate, "$.lead.coverageDate")
    } else if (dashboard.lead.kind === "digest") {
      const leadDigestId = dashboard.lead.digestId
      if (
        !dashboard.archive.some(({ digestId }) => digestId === leadDigestId)
      ) {
        throw new ContractDecodeError(
          "$.lead.digestId",
          "must name a digest in the permanent archive",
        )
      }
    }
  }
  return dashboard
}

export function decodeDailyCoachingDigestDetail(
  value: unknown,
): DailyCoachingDigestDetail {
  const digest = decodeDefinition<DailyCoachingDigestDetail>(
    "DailyCoachingDigestDetail",
    value,
  )
  validateDailyCoachingDigestSummary(digest, "$")
  requireNonEmpty([digest.timezone], "$.timezone")
  if (digest.priorities.length > 2) {
    throw new ContractDecodeError(
      "$.priorities",
      "must contain at most two coaching priorities",
    )
  }
  if (digest.games.length !== digest.gameCount) {
    throw new ContractDecodeError(
      "$.games",
      "must contain exactly gameCount Games",
    )
  }
  const learningPathCount = digest.games.reduce(
    (count, game) => count + game.learningPathCount,
    0,
  )
  if (learningPathCount !== digest.learningPathCount) {
    throw new ContractDecodeError(
      "$.learningPathCount",
      "must equal the sum of the included Game path counts",
    )
  }
  digest.games.forEach((game, index) =>
    requireTimestamp(game.endedAt, `$.games[${index}].endedAt`),
  )
  digest.priorities.forEach((priority, index) => {
    if (
      priority.supportingGameCount < 1 ||
      priority.supportingGameCount > digest.gameCount
    ) {
      throw new ContractDecodeError(
        `$.priorities[${index}].supportingGameCount`,
        "must count a non-empty subset of the included Games",
      )
    }
    if (
      priority.supportingGameImportIds.length !== priority.supportingGameCount
    ) {
      throw new ContractDecodeError(
        `$.priorities[${index}].supportingGameImportIds`,
        "must identify every supporting Game exactly once",
      )
    }
    const includedGameIds = new Set(
      digest.games.map(({ gameImportId }) => gameImportId),
    )
    const supportingGameIds = new Set(priority.supportingGameImportIds)
    if (
      supportingGameIds.size !== priority.supportingGameImportIds.length ||
      priority.supportingGameImportIds.some(
        (gameImportId) => !includedGameIds.has(gameImportId),
      )
    ) {
      throw new ContractDecodeError(
        `$.priorities[${index}].supportingGameImportIds`,
        "must be a unique subset of the included Games",
      )
    }
    if (priority.resources.length === 0) {
      throw new ContractDecodeError(
        `$.priorities[${index}].resources`,
        "must contain the exact learning resources",
      )
    }
  })
  return digest
}

export function decodeImportedGameListPage(
  value: unknown,
): ImportedGameListPage {
  const page = decodeDefinition<ImportedGameListPage>(
    "ImportedGameListPage",
    value,
  )
  if (page.games.length > 20) {
    throw new ContractDecodeError("$.games", "must contain at most 20 Games")
  }
  for (const [index, game] of page.games.entries()) {
    requireTimestamp(game.endedAt, `$.games[${index}].endedAt`)
  }
  requireUnique(
    page.games.map(({ gameImportId }) => gameImportId),
    "$.games",
  )
  for (let index = 1; index < page.games.length; index += 1) {
    if (
      Date.parse(page.games[index - 1]!.endedAt) <
      Date.parse(page.games[index]!.endedAt)
    ) {
      throw new ContractDecodeError(
        "$.games",
        "must be newest-first by played time",
      )
    }
  }
  if (page.nextCursor !== null && page.games.length !== 20) {
    throw new ContractDecodeError(
      "$.nextCursor",
      "may continue only after a full page",
    )
  }
  if (page.nextCursor !== null) {
    requireNonEmpty([page.nextCursor], "$.nextCursor")
  }
  return page
}

export function decodeReviewedGameSearchResult(
  value: unknown,
): ReviewedGameSearchResult {
  const result = decodeDefinition<ReviewedGameSearchResult>(
    "ReviewedGameSearchResult",
    value,
  )
  if (result.games.length > 20) {
    throw new ContractDecodeError("$.games", "must contain at most 20 Games")
  }
  requireUnique(
    result.games.map(({ reviewedGameKey }) => reviewedGameKey),
    "$.games",
  )
  for (const [index, game] of result.games.entries()) {
    const path = `$.games[${index}]`
    if ("endedAt" in game) {
      if (typeof game.endedAt !== "string") {
        throw new ContractDecodeError(
          `${path}.endedAt`,
          "must be a timestamp when present",
        )
      }
      requireTimestamp(game.endedAt, `${path}.endedAt`)
    }
    if (!game.digested && !game.imported) {
      throw new ContractDecodeError(path, "must be digested or imported")
    }
    const hasDigestIdentity =
      typeof game.digestId === "string" && typeof game.digestDate === "string"
    if (
      game.digested !== hasDigestIdentity ||
      (!game.digested && ("digestId" in game || "digestDate" in game))
    ) {
      throw new ContractDecodeError(
        path,
        "must carry digest identity exactly when digested",
      )
    }
  }
  const played = result.games.filter(
    (game): game is typeof game & { endedAt: string } =>
      typeof game.endedAt === "string",
  )
  for (let index = 1; index < played.length; index += 1) {
    if (
      Date.parse(played[index - 1]!.endedAt) <
      Date.parse(played[index]!.endedAt)
    ) {
      throw new ContractDecodeError(
        "$.games",
        "must be newest-first by played time",
      )
    }
  }
  if (played.length === 0) {
    if (
      "earliestPlayedAt" in result.coverage ||
      "latestPlayedAt" in result.coverage
    ) {
      throw new ContractDecodeError(
        "$.coverage",
        "must omit played-time bounds when no Game has play time",
      )
    }
  } else {
    if (
      typeof result.coverage.earliestPlayedAt !== "string" ||
      typeof result.coverage.latestPlayedAt !== "string"
    ) {
      throw new ContractDecodeError(
        "$.coverage",
        "must carry both played-time bounds when a Game has play time",
      )
    }
    requireTimestamp(
      result.coverage.earliestPlayedAt,
      "$.coverage.earliestPlayedAt",
    )
    requireTimestamp(
      result.coverage.latestPlayedAt,
      "$.coverage.latestPlayedAt",
    )
  }
  if (result.truncation.totalMatchCount < result.games.length) {
    throw new ContractDecodeError(
      "$.truncation.totalMatchCount",
      "must include every returned Game",
    )
  }
  if (result.truncation.kind === "truncated") {
    if (result.games.length !== 20 || result.truncation.totalMatchCount <= 20) {
      throw new ContractDecodeError(
        "$.truncation",
        "must describe a full truncated page",
      )
    }
    requireTimestamp(
      result.truncation.oldestReturnedAt,
      "$.truncation.oldestReturnedAt",
    )
    const oldestEndedAt = result.games[result.games.length - 1]!.endedAt
    if (
      typeof oldestEndedAt === "string" &&
      result.truncation.oldestReturnedAt !== oldestEndedAt
    ) {
      throw new ContractDecodeError(
        "$.truncation.oldestReturnedAt",
        "must equal the oldest returned Game play time",
      )
    }
  } else if (result.truncation.totalMatchCount !== result.games.length) {
    throw new ContractDecodeError(
      "$.truncation.totalMatchCount",
      "must equal the complete result count",
    )
  }
  return result
}

export function decodeReviewSessionPresentation(
  value: unknown,
): ReviewSessionPresentation {
  const presentation = decodeDefinition<ReviewSessionPresentation>(
    "ReviewSessionPresentation",
    value,
  )
  validatePresentation(presentation)
  return presentation
}

export function decodeReviewSessionPresentationAddition(
  value: unknown,
): ReviewSessionPresentationAddition {
  const addition = decodeDefinition<ReviewSessionPresentationAddition>(
    "ReviewSessionPresentationAddition",
    value,
  )
  if (
    addition.priorRevision < 1 ||
    addition.resultingRevision < addition.priorRevision ||
    addition.resultingRevision > addition.priorRevision + 1
  ) {
    throw new ContractDecodeError(
      "$.resultingRevision",
      "must equal the prior revision or its direct successor",
    )
  }
  if (
    addition.changedMomentIds.length !== 1 ||
    addition.changedMomentIds[0] !== addition.moment.momentId
  ) {
    throw new ContractDecodeError(
      "$.changedMomentIds",
      "must name the exact changed Review Moment",
    )
  }
  if (
    addition.changedFields.length !== 3 ||
    addition.changedFields[0] !== "animation" ||
    addition.changedFields[1] !== "moment" ||
    addition.changedFields[2] !== "selectedMomentId"
  ) {
    throw new ContractDecodeError(
      "$.changedFields",
      "must name the complete bounded presentation delta",
    )
  }
  if (
    addition.moment.handoff.gameImportId !== addition.gameImportId ||
    addition.moment.handoff.momentId !== addition.moment.momentId ||
    addition.moment.handoff.ply !== addition.moment.ply
  ) {
    throw new ContractDecodeError(
      "$.moment.handoff",
      "must target the exact added Review Moment",
    )
  }
  validatePresentationAnimation(
    {
      animation: addition.animation,
      moments: [addition.moment],
      version: addition.version,
    },
    new Set([addition.moment.momentId]),
  )
  return addition
}

export function decodeGameReviewSnapshot(value: unknown): GameReviewSnapshot {
  const snapshot = decodeDefinition<GameReviewSnapshot>(
    "GameReviewSnapshot",
    value,
  )
  requireIncreasing(
    snapshot.evaluationTimeline.map(({ ply }) => ply),
    "$.evaluationTimeline",
  )
  requireIncreasing(
    snapshot.moments.map(({ ply }) => ply),
    "$.moments",
  )
  requireUnique(
    snapshot.moments.map(({ momentId }) => momentId),
    "$.moments",
  )
  if (
    snapshot.evaluationTimeline.some(({ ply }) => ply > snapshot.maxPly) ||
    snapshot.moments.some(({ ply }) => ply > snapshot.maxPly)
  ) {
    throw new ContractDecodeError(
      "$.maxPly",
      "must include every presented ply",
    )
  }
  for (const [index, moment] of snapshot.moments.entries()) {
    const path = `$.moments[${index}]`
    // Stepping to the next Critical Moment is an index step, so a gap or a
    // reorder here is the difference between "next" and "some other moment".
    if (moment.index !== index) {
      throw new ContractDecodeError(
        `${path}.index`,
        "must be contiguous and zero-based in ply order",
      )
    }
    requireNonEmpty(
      [
        moment.moveLabel,
        moment.glyph,
        moment.title,
        moment.summary,
        moment.board.announcement,
      ],
      path,
    )
    requireUnique(
      moment.board.pieces.map(({ pieceId }) => pieceId),
      `${path}.board.pieces`,
    )
    requireUnique(
      moment.board.pieces.map(({ square }) => square),
      `${path}.board.pieces`,
    )
    if (
      moment.selection.kind === "pipelineCriticalMoment"
        ? moment.selection.criticalMomentId !== moment.momentId
        : moment.selection.ply !== moment.ply
    ) {
      throw new ContractDecodeError(
        `${path}.selection`,
        "must name the exact snapshot Review Moment",
      )
    }
    for (const [arrowIndex, arrow] of moment.arrows.entries()) {
      requireNonEmpty([arrow.label], `${path}.arrows[${arrowIndex}]`)
      if (arrow.from === arrow.to) {
        throw new ContractDecodeError(
          `${path}.arrows[${arrowIndex}]`,
          "must describe a move between two squares",
        )
      }
    }
    requireUnique(moment.sequenceKinds, `${path}.sequenceKinds`)
  }
  return snapshot
}

export function decodeReviewMomentSnapshot(
  value: unknown,
): ReviewMomentSnapshot {
  const snapshot = decodeDefinition<ReviewMomentSnapshot>(
    "ReviewMomentSnapshot",
    value,
  )
  validateSnapshotSequences(snapshot.sequences, "$")
  return snapshot
}

export function decodeMoveSequenceSnapshot(
  value: unknown,
): MoveSequenceSnapshot {
  const snapshot = decodeDefinition<MoveSequenceSnapshot>(
    "MoveSequenceSnapshot",
    value,
  )
  requireNonEmpty([snapshot.title], "$.title")
  validateSequenceMoves(snapshot.moves)
  return snapshot
}

export function decodeMoveSequencePresentation(
  value: unknown,
): MoveSequencePresentation {
  const presentation = decodeDefinition<MoveSequencePresentation>(
    "MoveSequencePresentation",
    value,
  )
  requireNonEmpty([presentation.title], "$.title")
  validateSequenceMoves(presentation.moves)
  return presentation
}

/**
 * A rendered continuation is one-based, contiguous, and every ply is a real
 * move on a real board, whichever address served it.
 */
function validateSequenceMoves(moves: MoveSequencePresentation["moves"]) {
  if (moves.length === 0) {
    throw new ContractDecodeError(
      "$.moves",
      "must contain at least one canonical move",
    )
  }
  moves.forEach((move, index) => {
    const path = `$.moves[${index}]`
    if (move.index !== index + 1) {
      throw new ContractDecodeError(
        `${path}.index`,
        "must be contiguous and one-based",
      )
    }
    requireNonEmpty([move.san, move.board.announcement], path)
    requireUnique(
      move.board.pieces.map(({ pieceId }) => pieceId),
      `${path}.board.pieces`,
    )
    requireUnique(
      move.board.pieces.map(({ square }) => square),
      `${path}.board.pieces`,
    )
    requireNonEmpty(
      move.board.pieces.map(({ pieceId }) => pieceId),
      `${path}.board.pieces`,
    )
    if (move.board.lastMove.from === move.board.lastMove.to) {
      throw new ContractDecodeError(
        `${path}.board.lastMove`,
        "must describe one move between distinct squares",
      )
    }
  })
}

/**
 * A Review Moment offers at most one continuation of each kind, and a
 * continuation's move count is what a surface renders before reading the moves.
 */
function validateSnapshotSequences(
  sequences: ReviewMomentSnapshot["sequences"],
  path: string,
) {
  requireUnique(
    sequences.map(({ kind }) => kind),
    `${path}.sequences`,
  )
  for (const [index, sequence] of sequences.entries()) {
    const sequencePath = `${path}.sequences[${index}]`
    requireNonEmpty([sequence.title], sequencePath)
    if (sequence.san.length !== sequence.moveCount) {
      throw new ContractDecodeError(
        `${sequencePath}.moveCount`,
        "must count the referenced moves",
      )
    }
  }
}

export async function decodeImportedGame(
  value: unknown,
): Promise<ImportedGame> {
  return decodeDefinition("ImportedGame", value)
}

export async function decodePositionSnapshot(
  value: unknown,
): Promise<PositionSnapshot> {
  const position = decodeDefinition<PositionSnapshot>("PositionSnapshot", value)
  await validatePositionSnapshot(position)
  return position
}

export async function decodeReviewSessionEvidencePacket(
  value: unknown,
): Promise<ReviewSessionEvidencePacket> {
  const packet = decodeDefinition<ReviewSessionEvidencePacket>(
    "ReviewSessionEvidencePacket",
    value,
  )
  await validateEvidencePacket(packet)
  return packet
}

export async function decodeEvidenceEntry(
  value: unknown,
): Promise<EvidenceEntry> {
  const entry = decodeDefinition<EvidenceEntry>("EvidenceEntry", value)
  validateEvidenceEntry(entry)
  return entry
}

function decodeDefinition<T>(name: string, value: unknown): T {
  validateContractDefinition(schemaDocument, name, value)
  return value as T
}

async function validateEvidencePacket(
  packet: ReviewSessionEvidencePacket,
): Promise<void> {
  for (const entry of packet.entries) validateEvidenceEntry(entry)
}

function validateEvidenceEntry(entry: EvidenceEntry): void {
  const dependencies = entry.metadata.dependencies
  for (let index = 1; index < dependencies.length; index += 1) {
    if (dependencies[index - 1]! >= dependencies[index]!) {
      throw new ContractDecodeError(
        "$.metadata.dependencies",
        "must be sorted and unique",
      )
    }
  }
  if (
    !entry.metadata.evidenceId.startsWith("sha256:") ||
    !entry.metadata.contentDigest.startsWith("sha256:")
  ) {
    throw new ContractDecodeError(
      "$.metadata",
      "must use SHA-256 evidence identities",
    )
  }
}

function validateCoreEvidenceRefs(core: ReviewSessionCoreContract): void {
  const ids = new Set(
    core.evidencePacket.entries.map((entry) => entry.metadata.evidenceId),
  )
  if (core.coachTurnContext.requiredEvidenceRefs.some((id) => !ids.has(id))) {
    throw new ContractDecodeError(
      "$.coachTurnContext.requiredEvidenceRefs",
      "must refer to evidence in the server-owned packet",
    )
  }
}

function validatePresentation(presentation: ReviewSessionPresentation): void {
  if (
    presentation.sessionRevision < 1 ||
    presentation.presentationRevision < 1
  ) {
    throw new ContractDecodeError(
      "$.sessionRevision",
      "presentation revisions must start at one",
    )
  }
  requireIncreasing(
    presentation.evaluationTimeline.map(({ ply }) => ply),
    "$.evaluationTimeline",
  )
  requireIncreasing(
    presentation.moments.map(({ ply }) => ply),
    "$.moments",
  )
  requireUnique(
    presentation.moments.map(({ momentId }) => momentId),
    "$.moments",
  )
  if (
    presentation.evaluationTimeline.some(
      ({ ply }) => ply > presentation.maxPly,
    ) ||
    presentation.moments.some(({ ply }) => ply > presentation.maxPly)
  ) {
    throw new ContractDecodeError(
      "$.maxPly",
      "must include every presented ply",
    )
  }

  const momentIds = new Set(
    presentation.moments.map(({ momentId }) => momentId),
  )
  if (
    presentation.selectedMomentId === null
      ? presentation.moments.length > 0
      : !momentIds.has(presentation.selectedMomentId)
  ) {
    throw new ContractDecodeError(
      "$.selectedMomentId",
      "must select one presented moment, or be null only when no moments exist",
    )
  }

  for (const [index, moment] of presentation.moments.entries()) {
    const path = `$.moments[${index}]`
    requireNonEmpty(
      [
        moment.moveLabel,
        moment.glyph,
        moment.title,
        moment.summary,
        moment.board.announcement,
      ],
      path,
    )
    requireUnique(
      moment.board.pieces.map(({ pieceId }) => pieceId),
      `${path}.board.pieces`,
    )
    requireUnique(
      moment.board.pieces.map(({ square }) => square),
      `${path}.board.pieces`,
    )
    requireNonEmpty(
      moment.board.pieces.map(({ pieceId }) => pieceId),
      `${path}.board.pieces`,
    )
    if (
      moment.handoff.gameImportId !== presentation.gameImportId ||
      moment.handoff.momentId !== moment.momentId ||
      moment.handoff.ply !== moment.ply ||
      (moment.handoff.selection.kind === "pipelineCriticalMoment"
        ? moment.handoff.selection.criticalMomentId !== moment.momentId
        : moment.handoff.selection.ply !== moment.ply)
    ) {
      throw new ContractDecodeError(
        `${path}.handoff`,
        "must target the exact presented Review Moment",
      )
    }
    for (const [arrowIndex, arrow] of moment.arrows.entries()) {
      requireNonEmpty([arrow.label], `${path}.arrows[${arrowIndex}]`)
      if (arrow.from === arrow.to) {
        throw new ContractDecodeError(
          `${path}.arrows[${arrowIndex}]`,
          "must describe a move between two squares",
        )
      }
    }
  }

  validatePresentationAnimation(presentation, momentIds)
}

function validatePresentationAnimation(
  presentation: Pick<
    ReviewSessionPresentation,
    "animation" | "moments" | "version"
  >,
  momentIds: ReadonlySet<string>,
) {
  const animation = presentation.animation
  if (!animation) return
  requireNonEmpty([animation.lineId], "$.animation")
  if (animation.version !== presentation.version) {
    throw new ContractDecodeError(
      "$.animation.version",
      "must match the containing presentation version",
    )
  }
  if (!momentIds.has(animation.reviewMomentId)) {
    throw new ContractDecodeError(
      "$.animation.reviewMomentId",
      "must refer to a presented moment",
    )
  }
  if (animation.frames.length === 0 || animation.frames.length > 8) {
    throw new ContractDecodeError(
      "$.animation.frames",
      "must contain between one and eight bounded frames",
    )
  }
  if (
    animation.frames.reduce((total, frame) => total + frame.durationMs, 0) >
    8_000
  ) {
    throw new ContractDecodeError(
      "$.animation.frames",
      "must not exceed eight seconds total duration",
    )
  }
  const initialMoment = presentation.moments.find(
    ({ momentId }) => momentId === animation.reviewMomentId,
  )!
  let previousPlacements = initialMoment.board.pieces
  animation.frames.forEach((frame, index) => {
    if (frame.index !== index) {
      throw new ContractDecodeError(
        `$.animation.frames[${index}].index`,
        "must be contiguous and zero-based",
      )
    }
    requireNonEmpty([frame.moveLabel], `$.animation.frames[${index}]`)
    if (frame.durationMs < 100 || frame.durationMs > 2_000) {
      throw new ContractDecodeError(
        `$.animation.frames[${index}].durationMs`,
        "must be between 100 and 2000 milliseconds",
      )
    }
    requireUnique(
      frame.placements.map(({ pieceId }) => pieceId),
      `$.animation.frames[${index}].placements`,
    )
    requireUnique(
      frame.placements.map(({ square }) => square),
      `$.animation.frames[${index}].placements`,
    )
    requireUnique(
      frame.motions.map(({ pieceId }) => pieceId),
      `$.animation.frames[${index}].motions`,
    )
    requireUnique(
      frame.removedPieceIds,
      `$.animation.frames[${index}].removedPieceIds`,
    )
    const previousById = new Map(
      previousPlacements.map((placement) => [placement.pieceId, placement]),
    )
    const currentById = new Map(
      frame.placements.map((placement) => [placement.pieceId, placement]),
    )
    const motionIds = new Set(frame.motions.map(({ pieceId }) => pieceId))
    const removedIds = new Set(frame.removedPieceIds)
    for (const [motionIndex, motion] of frame.motions.entries()) {
      const path = `$.animation.frames[${index}].motions[${motionIndex}]`
      const previous = previousById.get(motion.pieceId)
      const current = currentById.get(motion.pieceId)
      if (
        !previous ||
        !current ||
        previous.square !== motion.from ||
        current.square !== motion.to ||
        motion.from === motion.to
      ) {
        throw new ContractDecodeError(
          path,
          "must move one stable piece from its prior square to its authoritative placement",
        )
      }
    }
    for (const removedId of frame.removedPieceIds) {
      if (!previousById.has(removedId) || currentById.has(removedId)) {
        throw new ContractDecodeError(
          `$.animation.frames[${index}].removedPieceIds`,
          "must remove only pieces present in the prior frame",
        )
      }
    }
    for (const [pieceId, previous] of previousById) {
      const current = currentById.get(pieceId)
      if (!current) {
        if (!removedIds.has(pieceId)) {
          throw new ContractDecodeError(
            `$.animation.frames[${index}]`,
            "must explicitly identify every removed piece",
          )
        }
      } else if (
        previous.square === current.square
          ? motionIds.has(pieceId)
          : !motionIds.has(pieceId)
      ) {
        throw new ContractDecodeError(
          `$.animation.frames[${index}]`,
          "must describe every and only changed stable-piece squares as motions",
        )
      }
    }
    for (const pieceId of currentById.keys()) {
      if (!previousById.has(pieceId)) {
        throw new ContractDecodeError(
          `$.animation.frames[${index}].placements`,
          "must preserve server-authored stable piece identities",
        )
      }
    }
    previousPlacements = frame.placements
  })
}

function validateDailyCoachingDigestSummary(
  summary: DailyCoachingDigestSummary,
  path: string,
): void {
  requireDate(summary.coverageDate, `${path}.coverageDate`)
  requireTimestamp(summary.publishedAt, `${path}.publishedAt`)
  if (summary.digestId !== `daily-${summary.coverageDate}`) {
    throw new ContractDecodeError(
      `${path}.digestId`,
      "must identify the exact daily coverage date",
    )
  }
  if (summary.gameCount < 1) {
    throw new ContractDecodeError(
      `${path}.gameCount`,
      "must count at least one selected Game",
    )
  }
}

function requireDescendingPublishedAt(
  summaries: readonly DailyCoachingDigestSummary[],
  path: string,
): void {
  if (
    summaries.some(
      (summary, index) =>
        index > 0 &&
        Date.parse(summaries[index - 1]!.publishedAt) <
          Date.parse(summary.publishedAt),
    )
  ) {
    throw new ContractDecodeError(path, "must be ordered by publication time")
  }
}

function requireDate(value: string, path: string): void {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    throw new ContractDecodeError(path, "must be an ISO calendar date")
  }
  const parsed = new Date(`${value}T00:00:00Z`)
  if (
    Number.isNaN(parsed.valueOf()) ||
    parsed.toISOString().slice(0, 10) !== value
  ) {
    throw new ContractDecodeError(path, "must be a valid calendar date")
  }
}

function requireTimestamp(value: string, path: string): void {
  if (
    !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(
      value,
    ) ||
    Number.isNaN(Date.parse(value))
  ) {
    throw new ContractDecodeError(path, "must be a valid RFC 3339 timestamp")
  }
}

function requireIncreasing(values: readonly number[], path: string): void {
  if (values.some((value, index) => index > 0 && values[index - 1]! >= value)) {
    throw new ContractDecodeError(path, "must be strictly increasing")
  }
}

function requireUnique(values: readonly string[], path: string): void {
  if (new Set(values).size !== values.length) {
    throw new ContractDecodeError(path, "must contain unique values")
  }
}

function requireNonEmpty(values: readonly string[], path: string): void {
  if (values.some((value) => value.trim().length === 0)) {
    throw new ContractDecodeError(path, "must contain non-empty text")
  }
}
