// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrawClaimReason } from "./DrawClaimReason.js";

export type DrawClaimState = { "kind": "none" } | { "kind": "available", first: DrawClaimReason, rest: Array<DrawClaimReason>, };
