// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionEngineProvenance } from "./DecisionEngineProvenance.js";
import type { EngineAssessmentRef } from "./EngineAssessmentRef.js";
import type { EngineAssessmentScore } from "./EngineAssessmentScore.js";

export type EngineAssessment = { assessmentRef: EngineAssessmentRef, rank: number | null, score: EngineAssessmentScore, provenance: DecisionEngineProvenance, };
