// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionEngineProvenance } from "./DecisionEngineProvenance.js";
import type { EngineEvaluation } from "./EngineEvaluation.js";

export type EngineCandidateEvidence = { rank: number, rootMoveUci: string, evaluation: EngineEvaluation, variation: Array<string>, provenance: DecisionEngineProvenance, };
