// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateGap } from "./CandidateGap.js";
import type { EngineEvaluation } from "./EngineEvaluation.js";

/**
 * A Decision Candidate is scored either absolutely or relative to the best
 * move, never both, and never absolutely from a search that does not own the
 * absolute (ADR 0041).
 */
export type EngineAssessmentScore = { "kind": "absolute", evaluation: EngineEvaluation, } | { "kind": "behindBest", gap: CandidateGap, };
