// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionCandidateRef } from "./DecisionCandidateRef.js";
import type { EngineAssessmentRef } from "./EngineAssessmentRef.js";

export type EngineComparison = { preferredCandidateRef: DecisionCandidateRef, alternativeCandidateRef: DecisionCandidateRef, preferredAssessmentRef: EngineAssessmentRef, alternativeAssessmentRef: EngineAssessmentRef, };
