// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { MateOutcome } from "./MateOutcome.js";

export type EngineEvaluation = { "kind": "centipawns", value: number, perspective: Color, } | { "kind": "mate", outcome: MateOutcome, distancePlies: number, perspective: Color, };
