// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MateComparison } from "./MateComparison.js";

export type EvaluationLoss = { "kind": "centipawns", value: number, } | { "kind": "mate", best: MateComparison, selected: MateComparison, };
