// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactDigest } from "./ArtifactDigest.js";
import type { EloRating } from "./EloRating.js";

export type EvidenceProvenance = { "kind": "derived", producer: string, } | { "kind": "stockfish", version: string, binaryDigest: ArtifactDigest, depth: number, threads: number, hashMib: number, } | { "kind": "maia", package: string, model: string, image: string, modelDigest: ArtifactDigest, configDigest: ArtifactDigest, playerElo: EloRating, opponentElo: EloRating, candidateLimit: number, } | { "kind": "player" };
