// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactDigest } from "./ArtifactDigest.js";
import type { EvidenceId } from "./EvidenceId.js";
import type { EvidenceProvenance } from "./EvidenceProvenance.js";

export type EvidenceMetadata = { evidenceId: EvidenceId, dependencies: Array<EvidenceId>, contentDigest: ArtifactDigest, provenance: EvidenceProvenance, };
