// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchEvidence } from "./BranchEvidence.js";
import type { EngineAnalysisEvidence } from "./EngineAnalysisEvidence.js";
import type { EvidenceMetadata } from "./EvidenceMetadata.js";
import type { HumanMoveModelEvidence } from "./HumanMoveModelEvidence.js";
import type { PositionRef } from "./PositionRef.js";
import type { PositionSnapshot } from "./PositionSnapshot.js";
import type { ProvenanceFact } from "./ProvenanceFact.js";

export type EvidenceEntry = { "kind": "position", metadata: EvidenceMetadata, position: PositionSnapshot, } | { "kind": "engineAnalysis", metadata: EvidenceMetadata, positionRef: PositionRef, analysis: EngineAnalysisEvidence, } | { "kind": "humanMoveModel", metadata: EvidenceMetadata, positionRef: PositionRef, analysis: HumanMoveModelEvidence, } | { "kind": "branch", metadata: EvidenceMetadata, branch: BranchEvidence, } | { "kind": "provenance", metadata: EvidenceMetadata, fact: ProvenanceFact, };
