// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateGenerationProof } from "./CandidateGenerationProof.js";
import type { ConceptValidationProof } from "./ConceptValidationProof.js";
import type { DecisionCandidateRef } from "./DecisionCandidateRef.js";
import type { ExplanationPathAttribution } from "./ExplanationPathAttribution.js";
import type { ExplanationPathRef } from "./ExplanationPathRef.js";
import type { KnowledgeActivation } from "./KnowledgeActivation.js";
import type { SemanticOutcomeRef } from "./SemanticOutcomeRef.js";

export type ExplanationPath = { pathRef: ExplanationPathRef, attribution: ExplanationPathAttribution, candidateRef: DecisionCandidateRef, knowledgeActivation: KnowledgeActivation, candidateGenerationProof: CandidateGenerationProof | null, conceptValidationProof: ConceptValidationProof, outcomeRefs: Array<SemanticOutcomeRef>, };
