// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameReviewOpeningPrinciple } from "./GameReviewOpeningPrinciple.js";
import type { GameReviewTeachingTheme } from "./GameReviewTeachingTheme.js";
import type { GameReviewTeachingVocabularyVersion } from "./GameReviewTeachingVocabularyVersion.js";

export type GameReviewTeachingFacts = { vocabularyVersion: GameReviewTeachingVocabularyVersion, themes: Array<GameReviewTeachingTheme>, openingPrinciples: Array<GameReviewOpeningPrinciple>, };
