// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameReviewEvaluationDisplay } from "./GameReviewEvaluationDisplay.js";

/**
 * Presentation-ready evaluation rendering for a Critical Moment. Scores and
 * labels are expressed from White's perspective; prose quotes them verbatim
 * instead of converting centipawns or flipping perspectives.
 */
export type GameReviewMomentDisplay = { playedAnnotation?: string | null, bestEvaluation: GameReviewEvaluationDisplay, playedEvaluation: GameReviewEvaluationDisplay, lossPawns?: string | null, };
