// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameInputSource = { "kind": "lichessUrl", url: string, } | { "kind": "chessComUrl", url: string, } | { "kind": "pastedPgn", pgn: string, } | { "kind": "localPgnFile", path: string, };
