// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImprovementCorrection } from "./ImprovementCorrection.js";
import type { NeutralReviewReason } from "./NeutralReviewReason.js";
import type { PositiveHighlightGrade } from "./PositiveHighlightGrade.js";
import type { PositiveHighlightQualification } from "./PositiveHighlightQualification.js";

/**
 * The teaching result for one reviewed move. Neutral is only valid for a
 * Player-selected move; automatic selection operates on the two Critical
 * Moment variants.
 */
export type GameReviewMomentClassification = { "kind": "positiveHighlight", qualification: PositiveHighlightQualification, grade: PositiveHighlightGrade, } | { "kind": "improvementOpportunity", correction: ImprovementCorrection, } | { "kind": "neutral", reasons: Array<NeutralReviewReason>, };
