// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameReviewPieceRole } from "./GameReviewPieceRole.js";

export type GameReviewMechanismPayoff = { "kind": "mate" } | { "kind": "promotion" } | { "kind": "winsMaterialOutright", role: GameReviewPieceRole, } | { "kind": "winsMaterialNet", role: GameReviewPieceRole, netPawnUnits: number, } | { "kind": "queenExchange" };
