// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameReviewAdvantageStanding } from "./GameReviewAdvantageStanding.js";
import type { GameReviewResidualClassification } from "./GameReviewResidualClassification.js";

export type GameReviewResidualOutcome = { standingBefore: GameReviewAdvantageStanding, standingAfter: GameReviewAdvantageStanding, classification: GameReviewResidualClassification, };
