// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameReviewCriticalMoment } from "./GameReviewCriticalMoment.js";
import type { GameReviewEvaluationPoint } from "./GameReviewEvaluationPoint.js";
import type { GameReviewPlayerProfile } from "./GameReviewPlayerProfile.js";
import type { GameReviewPositionView } from "./GameReviewPositionView.js";
import type { LearningPlan } from "./LearningPlan.js";

export type GameReview = { summary: string, playerProfile: GameReviewPlayerProfile, criticalMoments: Array<GameReviewCriticalMoment>, positionViews: Array<GameReviewPositionView>, evaluationTimeline: Array<GameReviewEvaluationPoint>, learningPlan: LearningPlan, };
