// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { EngineEvaluation } from "./EngineEvaluation.js";
import type { PositionSnapshot } from "./PositionSnapshot.js";

export type GameReviewPositionView = { criticalMomentId: CriticalMomentId, ply: number, positionSnapshot: PositionSnapshot, textBoard: string, evaluation: EngineEvaluation, };
