// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameReviewPieceRole } from "./GameReviewPieceRole.js";

export type GameReviewPlayedMoveEffect = { "kind": "capturedPiece", role: GameReviewPieceRole, square: string, } | { "kind": "advancedPassedPawn", toSquare: string, } | { "kind": "attackedPiece", role: GameReviewPieceRole, square: string, } | { "kind": "allowsQueenExchange" };
