// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Probability } from "./Probability.js";

export type GameReviewHumanComparison = { mostLikelyMoveUci: string, mostLikelyProbability: Probability, playedMoveProbability: Probability | null, playedMoveRank: number | null, playedMoveIsHumanLikely: boolean, };
