// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { CriticalMomentComment } from "./CriticalMomentComment.js";
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { DecisionExplanation } from "./DecisionExplanation.js";
import type { DecisionExplanationRef } from "./DecisionExplanationRef.js";
import type { DecisionLearningOutcome } from "./DecisionLearningOutcome.js";
import type { GameReviewCriticalMomentCategory } from "./GameReviewCriticalMomentCategory.js";
import type { GameReviewHumanComparison } from "./GameReviewHumanComparison.js";
import type { GameReviewMomentClassification } from "./GameReviewMomentClassification.js";
import type { GameReviewMomentDisplay } from "./GameReviewMomentDisplay.js";
import type { GameReviewMomentProvenance } from "./GameReviewMomentProvenance.js";
import type { GameReviewObjectiveComparison } from "./GameReviewObjectiveComparison.js";
import type { GameReviewPlayedMoveEffect } from "./GameReviewPlayedMoveEffect.js";
import type { GameReviewResidualOutcome } from "./GameReviewResidualOutcome.js";
import type { GameReviewTacticalMechanism } from "./GameReviewTacticalMechanism.js";
import type { GameReviewTeachingFacts } from "./GameReviewTeachingFacts.js";
import type { PlayedMoveOutcomeEvidence } from "./PlayedMoveOutcomeEvidence.js";
import type { PositionPhase } from "./PositionPhase.js";
import type { ReviewMomentLearningMaterial } from "./ReviewMomentLearningMaterial.js";

export type GameReviewCriticalMoment = { criticalMomentId: CriticalMomentId, ply: number, moveNumber: number, side: Color, playedSan: string, positionPhase: PositionPhase, classification: GameReviewMomentClassification, provenance: GameReviewMomentProvenance, category: GameReviewCriticalMomentCategory, objective: GameReviewObjectiveComparison, human: GameReviewHumanComparison, effects: Array<GameReviewPlayedMoveEffect>, residualOutcome: GameReviewResidualOutcome, playedMoveOutcome: PlayedMoveOutcomeEvidence, mechanism?: GameReviewTacticalMechanism | null, teaching: GameReviewTeachingFacts, 
/**
 * Addresses the proof aggregate without carrying it.
 *
 * The aggregate is audit-only and dominates a review's bytes, so the
 * delivered payload keeps the reference and drops the proof. The
 * reference stays resolvable against the durable review.
 */
decisionExplanationRef?: DecisionExplanationRef | null, decisionExplanation?: DecisionExplanation | null, 
/**
 * What the chess-concept learning pass established for this moment.
 * Opening Learning Tracks are selected independently and may coexist.
 */
decisionLearningOutcome: DecisionLearningOutcome, learningMaterial: ReviewMomentLearningMaterial, display: GameReviewMomentDisplay, comment?: CriticalMomentComment | null, };
