// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameReviewLineMove } from "./GameReviewLineMove.js";
import type { GameReviewPlayedMoveEffect } from "./GameReviewPlayedMoveEffect.js";

export type GameReviewObjectiveLines = { best: Array<GameReviewLineMove>, refutation: Array<GameReviewLineMove>, 
/**
 * What the opponent's first reply in the refutation line does, derived by
 * the same rule as the played move's own effects.
 *
 * The line already says which move the opponent has; this says why it is a
 * resource, which is the half a Player needs and the half prose could only
 * invent. Empty when that reply is quiet: a move that takes nothing and
 * attacks nothing supports no claim, and none is offered.
 */
refutationEffects?: Array<GameReviewPlayedMoveEffect>, 
/**
 * What the best line's first move does, by the same rule again.
 *
 * On an Improvement Opportunity that move is the better move, and this is
 * the only fact about it beyond its notation: the line says which move,
 * this says what it takes or hits. On a Positive Highlight the best move
 * is usually the played move, whose effects already sit on the moment, so
 * nothing reads this there. Empty when the move is quiet.
 */
bestMoveEffects?: Array<GameReviewPlayedMoveEffect>, };
