// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineEvaluation } from "./EngineEvaluation.js";
import type { GameReviewObjectiveLines } from "./GameReviewObjectiveLines.js";

export type GameReviewObjectiveComparison = { bestMoveUci: string, playedMoveUci: string, bestEvaluation: EngineEvaluation, playedEvaluation: EngineEvaluation, centipawnLoss: number | null, principalVariation: Array<string>, lines?: GameReviewObjectiveLines | null, };
