// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EloRating } from "./EloRating.js";
import type { GameReviewPlayerLevel } from "./GameReviewPlayerLevel.js";

export type GameReviewPlayerProfile = { elo: EloRating, level: GameReviewPlayerLevel, coachingFocus: string, };
