// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { EloRating } from "./EloRating.js";
import type { GameImportId } from "./GameImportId.js";
import type { GameReviewSnapshotMoment } from "./GameReviewSnapshotMoment.js";
import type { GameReviewSnapshotVersion } from "./GameReviewSnapshotVersion.js";
import type { OpeningMetadata } from "./OpeningMetadata.js";
import type { ReviewSessionPresentationEvaluationPoint } from "./ReviewSessionPresentationEvaluationPoint.js";
import type { ReviewSessionPresentationSource } from "./ReviewSessionPresentationSource.js";
import type { ReviewSide } from "./ReviewSide.js";

/**
 * Everything one Game Review renders as, addressed by its Game Import ID.
 *
 * A surface holding this needs nothing else and negotiates nothing: no Review
 * Session, no revision to reconcile, no recovery tier. Reading it is the whole
 * of rehydration, so first paint, a page refresh, and a year-old conversation
 * all render from the same bytes.
 */
export type GameReviewSnapshot = { version: GameReviewSnapshotVersion, gameImportId: GameImportId, source: ReviewSessionPresentationSource, opening: OpeningMetadata, reviewSide: ReviewSide, eloRating: EloRating, orientation: Color, maxPly: number, evaluationTimeline: Array<ReviewSessionPresentationEvaluationPoint>, 
/**
 * Ordered by ply, so "the next Critical Moment" is an index step.
 */
moments: Array<GameReviewSnapshotMoment>, };
