// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameReviewLineMove } from "./GameReviewLineMove.js";
import type { GameReviewMechanismPayoff } from "./GameReviewMechanismPayoff.js";

export type GameReviewTacticalMechanism = { moves: Array<GameReviewLineMove>, forcingIndex: number, payoff: GameReviewMechanismPayoff, };
