// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderTimingSummary } from "./ProviderTimingSummary.js";

export type GameImportTiming = { runtimeStartupMilliseconds?: number | null, totalPipelineMilliseconds: number, engineAnalysis: ProviderTimingSummary, humanMoveModel: ProviderTimingSummary, };
