// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveSequencePresentationKind } from "./MoveSequencePresentationKind.js";

/**
 * One canonical continuation a Review Moment offers.
 *
 * The moment and the kind are the reference: a Review Moment offers at most
 * one line of each kind, so nothing has to be minted, handed out, or kept
 * alive for a surface to name the line it wants played out. The moves
 * themselves are a separate read.
 */
export type GameReviewSnapshotSequence = { kind: MoveSequencePresentationKind, title: string, moveCount: number, san: Array<string>, };
