// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { DecisionLearningOutcome } from "./DecisionLearningOutcome.js";
import type { GameReviewEvaluationDisplay } from "./GameReviewEvaluationDisplay.js";
import type { MoveSequencePresentationKind } from "./MoveSequencePresentationKind.js";
import type { ReviewMomentLearningMaterial } from "./ReviewMomentLearningMaterial.js";
import type { ReviewMomentSelection } from "./ReviewMomentSelection.js";
import type { ReviewSessionPresentationArrow } from "./ReviewSessionPresentationArrow.js";
import type { ReviewSessionPresentationBoard } from "./ReviewSessionPresentationBoard.js";
import type { ReviewSessionPresentationMomentKind } from "./ReviewSessionPresentationMomentKind.js";
import type { ReviewSessionPresentationMomentTone } from "./ReviewSessionPresentationMomentTone.js";

export type GameReviewSnapshotMoment = { 
/**
 * Position in the ordered set, so a surface can step without searching.
 */
index: number, momentId: CriticalMomentId, ply: number, moveLabel: string, kind: ReviewSessionPresentationMomentKind, tone: ReviewSessionPresentationMomentTone, glyph: string, title: string, summary: string, selection: ReviewMomentSelection, decisionLearningOutcome: DecisionLearningOutcome, learningMaterial: ReviewMomentLearningMaterial, board: ReviewSessionPresentationBoard, arrows: Array<ReviewSessionPresentationArrow>, playedEvaluation: GameReviewEvaluationDisplay, bestEvaluation: GameReviewEvaluationDisplay, 
/**
 * Which continuations this moment offers, named and nothing more.
 *
 * The selector renders a moment's board, arrows, and evaluations; it never
 * renders a line. Carrying each line's title, length, and SAN here would
 * put every moment's moves in the payload of a card that shows none of
 * them, so the moves stay where they are read: `ReviewMomentSnapshot` for
 * the descriptors, `MoveSequenceSnapshot` for the line played out.
 */
sequenceKinds: Array<MoveSequencePresentationKind>, };
