// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One move inside a proof, named the way a coach would name it.
 */
export type GroundedStep = { uci: string, san: string, 
/**
 * The position the step produces.
 */
fen: string, };
