// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CriticalMomentComment } from "./CriticalMomentComment.js";
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { DecisionExplanationRef } from "./DecisionExplanationRef.js";
import type { DecisionLearningOutcome } from "./DecisionLearningOutcome.js";
import type { GameImportId } from "./GameImportId.js";
import type { GameReviewObjectiveLines } from "./GameReviewObjectiveLines.js";
import type { GroundedExplanation } from "./GroundedExplanation.js";
import type { MoveSequenceOrigin } from "./MoveSequenceOrigin.js";

/**
 * One Review Moment's grounded detail, addressed by its Game Import and its ID.
 *
 * The Game Review that contains the moment is a separate read, so nothing here
 * restates the review, the imported Game, or the other moments. What is left is
 * the two things a moment read alone can answer: the continuations this moment
 * offers, the resolved proof behind what the coach may say about it, and the
 * published Review Moment Comment when the Review Annotation Store has one.
 */
export type GroundedReviewMomentDetail = { gameImportId: GameImportId, reviewMomentId: CriticalMomentId, ply: number, continuation: MoveSequenceOrigin, 
/**
 * The frozen engine best line and played-move refutation, already SAN
 * rendered. Both continuations come from here rather than from candidate
 * evidence, so a rendered sequence and a coached one are the same line.
 */
objectiveLines: GameReviewObjectiveLines | null, 
/**
 * Addresses the audit-only proof aggregate without carrying it.
 */
explanationRef: DecisionExplanationRef | null, decisionLearningOutcome: DecisionLearningOutcome, explanation: GroundedExplanation | null, 
/**
 * The published Review Moment Comment for this Player and Review Moment.
 *
 * Absence means none has been published yet, not that authoring failed.
 * The comment is the only canonical place a Coach Intent Hypothesis may
 * appear (ADR 0026).
 */
comment: CriticalMomentComment | null, };
