// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { GroundedMaterialEvent } from "./GroundedMaterialEvent.js";
import type { MaterialValuePolicyVersion } from "./MaterialValuePolicyVersion.js";

export type GroundedMaterialTransaction = { perspective: Color, events: Array<GroundedMaterialEvent>, netConventionalValueDelta: number, valuePolicyVersion: MaterialValuePolicyVersion, };
