// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomicChessFactData } from "./AtomicChessFactData.js";
import type { CurriculumLearningConcept } from "./CurriculumLearningConcept.js";
import type { ExplanationPathAttribution } from "./ExplanationPathAttribution.js";
import type { ExplanationPathRef } from "./ExplanationPathRef.js";
import type { GroundedCandidate } from "./GroundedCandidate.js";
import type { GroundedMaterialTransaction } from "./GroundedMaterialTransaction.js";
import type { GroundedStep } from "./GroundedStep.js";
import type { PositionGoal } from "./PositionGoal.js";

/**
 * One selected Explanation Path with every reference resolved.
 *
 * A path that cannot be resolved whole is not delivered at all. Optional
 * fields mean the durable proof did not establish that kind of evidence, not
 * that grounding lost it.
 */
export type GroundedExplanationPath = { pathRef: ExplanationPathRef, attribution: ExplanationPathAttribution, 
/**
 * The activated concept under its curriculum name.
 */
concept: CurriculumLearningConcept, candidate: GroundedCandidate, 
/**
 * The proof-backed goal that generated this candidate, when one exists.
 * It is candidate-discovery evidence, never a claim about Engine intent.
 */
positionGoal?: PositionGoal | null, 
/**
 * Every material exchange in the selected candidate's complete retained
 * line, including events beyond the short variation a coach recites.
 */
materialTransaction?: GroundedMaterialTransaction | null, 
/**
 * The move that creates the threat.
 */
causalStep: GroundedStep, 
/**
 * The move that collects on it.
 */
payoffStep: GroundedStep, supportingFacts: Array<AtomicChessFactData>, };
