// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionCandidateOrigin } from "./DecisionCandidateOrigin.js";
import type { EngineAssessmentScore } from "./EngineAssessmentScore.js";
import type { SemanticOutcomeData } from "./SemanticOutcomeData.js";

/**
 * One Decision Candidate as a reader can speak about it.
 *
 * `line_steps` is deliberately absent: ordinary per-ply machine detail is
 * replaced by the short spoken variation, while the path-local material
 * transaction preserves every later exchange relevant to coaching.
 */
export type GroundedCandidate = { rootMoveUci: string, san: string, origins: Array<DecisionCandidateOrigin>, evaluation: EngineAssessmentScore, outcomes: Array<SemanticOutcomeData>, 
/**
 * The candidate's line in SAN, truncated to the plies a coach would
 * actually recite. SAN rather than UCI because prose quotes it verbatim.
 */
retainedVariation: Array<string>, };
