// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { PieceAtSquare } from "./PieceAtSquare.js";
import type { PieceRole } from "./PieceRole.js";
import type { Square } from "./Square.js";

export type GroundedMaterialEvent = { "kind": "capture", linePly: number, uci: string, san: string, mover: Color, captured: PieceAtSquare, conventionalValueDelta: number, } | { "kind": "promotion", linePly: number, uci: string, san: string, mover: Color, pawnFromSquare: Square, promotionRole: PieceRole, conventionalValueDelta: number, } | { "kind": "captureAndPromotion", linePly: number, uci: string, san: string, mover: Color, captured: PieceAtSquare, pawnFromSquare: Square, promotionRole: PieceRole, conventionalValueDelta: number, };
