// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionExplanationRef } from "./DecisionExplanationRef.js";
import type { GroundedCandidate } from "./GroundedCandidate.js";
import type { GroundedExplanationPath } from "./GroundedExplanationPath.js";
import type { ProofCapability } from "./ProofCapability.js";

/**
 * The proof behind one Review Moment, resolved into names and moves.
 *
 * `capability` governs what a host model may claim — whether it may say a
 * candidate is better than the played move or only that a concept is soundly
 * present — so it stays on the wire even though nothing renders it.
 *
 * Every field below is resolved or the whole aggregate is withheld. A proof
 * delivered with its concept or its moves missing still carries a capability
 * that licenses a claim, and a reader would have nothing to make the claim
 * out of — which is exactly the shape a model invents into.
 */
export type GroundedExplanation = { explanationRef: DecisionExplanationRef, capability: ProofCapability, paths: Array<GroundedExplanationPath>, candidates: Array<GroundedCandidate>, };
