// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One prior HostTurn's Player message and grounded answer.
 *
 * Capability results never re-enter this memory. The active branch stays on
 * screen and is read from the Review Session actor, not from this payload.
 */
export type HostTurnPriorTurn = { message: string, answer: string, };
