// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlternativeMoveId } from "./AlternativeMoveId.js";

/**
 * A line the web board should show after a completed HostTurn.
 *
 * `engineBest` and `playedMoveRefutation` name a pre-loaded objective line
 * kind. `alternativeMove` names a line returned this turn or already on screen.
 */
export type HostTurnShowLine = { "kind": "engineBest" } | { "kind": "playedMoveRefutation" } | { "kind": "alternativeMove", alternativeMoveId: AlternativeMoveId, };
