// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the pinned model refused to answer this HostTurn (D6).
 *
 * The engine renders the Player-facing sentence; the model never writes it.
 */
export type HostTurnRefusalReason = "notAboutThisReview" | "notAboutChess" | "unsafeRequest";
