// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fixed Player-facing HostTurn progress labels (D9).
 *
 * These are product language, never capability names. The engine sends the
 * closed kind; Central Host maps it to the display string.
 */
export type HostTurnStepLabel = "lookingAtAnotherMoment" | "checkingThatLine" | "writing";
