// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EloRating } from "./EloRating.js";
import type { HumanMoveCandidateEvidence } from "./HumanMoveCandidateEvidence.js";
import type { ProbabilityState } from "./ProbabilityState.js";

export type HumanMoveModelEvidence = { playerElo: EloRating, opponentElo: EloRating, candidates: Array<HumanMoveCandidateEvidence>, winProbability: ProbabilityState, };
