// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Probability } from "./Probability.js";

export type HumanMoveCandidateEvidence = { uci: string, probability: Probability, rank: number, };
