// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactDigest } from "./ArtifactDigest.js";
import type { CanonicalGameId } from "./CanonicalGameId.js";

export type ImportProvenance = { "kind": "lichess", canonicalGameId: CanonicalGameId, sideQualifiedUrl: string, canonicalUrl: string, exportContractVersion: string, capturedAt: string, responseDigest: ArtifactDigest, pgnDigest: ArtifactDigest, } | { "kind": "chessCom", canonicalGameId: CanonicalGameId, canonicalUrl: string, fetchContractVersion: string, capturedAt: string, responseDigest: ArtifactDigest, pgnDigest: ArtifactDigest, } | { "kind": "pastedPgn", pgnDigest: ArtifactDigest, } | { "kind": "localPgn", pgnDigest: ArtifactDigest, };
