// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameImportId } from "./GameImportId.js";
import type { ImportedGameOpening } from "./ImportedGameOpening.js";
import type { ImportedGameOutcome } from "./ImportedGameOutcome.js";
import type { ImportedGameProvider } from "./ImportedGameProvider.js";
import type { ImportedGameReviewSide } from "./ImportedGameReviewSide.js";
import type { ImportedGameTimeControlClass } from "./ImportedGameTimeControlClass.js";

export type ImportedGameListItem = { gameImportId: GameImportId, provider: ImportedGameProvider, reviewSide: ImportedGameReviewSide, outcome: ImportedGameOutcome | null, opening: ImportedGameOpening | null, opponentName: string | null, endedAt: string, timeControlRaw: string | null, timeControlClass: ImportedGameTimeControlClass | null, learningPathCount: number, };
