// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportedGameListItem } from "./ImportedGameListItem.js";

export type ImportedGameListPage = { games: Array<ImportedGameListItem>, nextCursor: string | null, };
