// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanonicalCompletedGame } from "./CanonicalCompletedGame.js";
import type { ImportProvenance } from "./ImportProvenance.js";
import type { ResolvedEloProfile } from "./ResolvedEloProfile.js";
import type { ReviewSide } from "./ReviewSide.js";

export type ImportedGame = { game: CanonicalCompletedGame, reviewSide: ReviewSide, eloProfile: ResolvedEloProfile, provenance: ImportProvenance, };
