// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardTerminalOutcome } from "./BoardTerminalOutcome.js";
import type { EngineEvaluation } from "./EngineEvaluation.js";

export type ImprovementOutcome = { "kind": "improvedAnalyzed", betterEvaluation: EngineEvaluation, } | { "kind": "avoidedTerminal", avoided: BoardTerminalOutcome, };
