// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImprovementOutcome } from "./ImprovementOutcome.js";

export type ImprovementCorrection = { betterMoveUci: string, betterMoveSan: string, outcome: ImprovementOutcome, };
