// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomicFactRef } from "./AtomicFactRef.js";
import type { KnowledgeNodeRef } from "./KnowledgeNodeRef.js";
import type { KnowledgeRuleRef } from "./KnowledgeRuleRef.js";

export type KnowledgeActivation = { conceptNodeRef: KnowledgeNodeRef, recognitionRuleRef: KnowledgeRuleRef, supportingFactRefs: Array<AtomicFactRef>, };
