// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LearningResourceCatalogVersion = "learning-resources/2026-07-25" | "learning-resources/2026-08-03";
