// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LearningPlanSelectionPolicyVersion } from "./LearningPlanSelectionPolicyVersion.js";
import type { LearningResourceCatalogVersion } from "./LearningResourceCatalogVersion.js";
import type { LearningTrack } from "./LearningTrack.js";

export type LearningPlan = { selectionPolicyVersion: LearningPlanSelectionPolicyVersion, resourceCatalogVersion: LearningResourceCatalogVersion, 
/**
 * Recommendations in pedagogical order: evidence rank, `Refines`
 * clustering, then hard `Prerequisite` constraints.
 */
tracks: Array<LearningTrack>, };
