// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExplanationPathRef } from "./ExplanationPathRef.js";
import type { OpeningLearningEvidence } from "./OpeningLearningEvidence.js";

export type LearningTrackSupportBasis = { "kind": "decisionExplanation", explanationPathRef: ExplanationPathRef, } | { "kind": "opening", evidence: OpeningLearningEvidence, };
