// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LearningResourceId } from "./LearningResourceId.js";
import type { LearningResourceKind } from "./LearningResourceKind.js";
import type { LearningResourceRole } from "./LearningResourceRole.js";

export type LearningResource = { resourceId: LearningResourceId, role: LearningResourceRole, kind: LearningResourceKind, title: string, canonicalUrl: string, };
