// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeliverySurface } from "./DeliverySurface.js";
import type { LearningPathRef } from "./LearningPathRef.js";
import type { LearningPathVote } from "./LearningPathVote.js";

export type LearningPathFeedbackState = { learningPathRef: LearningPathRef, currentVote: LearningPathVote | null, exposedSurfaces: Array<DeliverySurface>, };
