// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LearningResource } from "./LearningResource.js";
import type { LearningTrackKey } from "./LearningTrackKey.js";
import type { LearningTrackSupport } from "./LearningTrackSupport.js";

export type LearningTrack = { key: LearningTrackKey, support: Array<LearningTrackSupport>, resources: Array<LearningResource>, };
