// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { LearningPathRef } from "./LearningPathRef.js";
import type { LearningTrackSupportBasis } from "./LearningTrackSupportBasis.js";

export type LearningTrackSupport = { "purpose": "improvement", learningPathRef: LearningPathRef, criticalMomentId: CriticalMomentId, ply: number, basis: LearningTrackSupportBasis, } | { "purpose": "reinforcement", learningPathRef: LearningPathRef, criticalMomentId: CriticalMomentId, ply: number, basis: LearningTrackSupportBasis, };
