// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurriculumLearningConcept } from "./CurriculumLearningConcept.js";
import type { LearningResourceMappingId } from "./LearningResourceMappingId.js";

export type LearningTrackKey = { "kind": "curriculum", concept: CurriculumLearningConcept, } | { "kind": "opening", resourceMappingId: LearningResourceMappingId, };
