// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MateOutcome } from "./MateOutcome.js";

export type MateComparison = { "kind": "notForced" } | { "kind": "forced", outcome: MateOutcome, distancePlies: number, };
