// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MaterialInventory = { pawns: number, knights: number, bishops: number, rooks: number, queens: number, };
