// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { ReviewSide } from "./ReviewSide.js";

/**
 * Where a Review Moment's continuations start and which way they are read.
 *
 * The engine line continues from the position the Player faced; the refutation
 * continues from the position their move produced. `reviewed_move_uci` is what
 * separates the two, so a surface can place both without re-deriving the Game.
 */
export type MoveSequenceOrigin = { fen: string, sideToMove: Color, reviewSide: ReviewSide, reviewedMoveUci: string | null, };
