// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { GameImportId } from "./GameImportId.js";
import type { GameReviewSnapshotVersion } from "./GameReviewSnapshotVersion.js";
import type { MoveSequencePresentationKind } from "./MoveSequencePresentationKind.js";
import type { MoveSequencePresentationMove } from "./MoveSequencePresentationMove.js";

/**
 * One canonical continuation played out ply by ply, addressed by its kind.
 *
 * Nothing is minted and nothing expires: a Review Moment offers at most one
 * line of each kind, so the kind is the reference and the same address answers
 * with the same moves forever.
 */
export type MoveSequenceSnapshot = { version: GameReviewSnapshotVersion, gameImportId: GameImportId, reviewMomentId: CriticalMomentId, kind: MoveSequencePresentationKind, title: string, orientation: Color, moves: Array<MoveSequencePresentationMove>, };
