// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { GameImportId } from "./GameImportId.js";
import type { MoveSequencePresentationKind } from "./MoveSequencePresentationKind.js";
import type { MoveSequencePresentationMove } from "./MoveSequencePresentationMove.js";
import type { MoveSequencePresentationVersion } from "./MoveSequencePresentationVersion.js";
import type { MoveSequenceRef } from "./MoveSequenceRef.js";

export type MoveSequencePresentation = { version: MoveSequencePresentationVersion, sequenceRef: MoveSequenceRef, gameImportId: GameImportId, reviewMomentId: CriticalMomentId, kind: MoveSequencePresentationKind, title: string, orientation: Color, moves: Array<MoveSequencePresentationMove>, };
