// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MoveInput = { "kind": "uci", uci: string, } | { "kind": "san", san: string, };
