// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveSequencePresentationBoard } from "./MoveSequencePresentationBoard.js";

export type MoveSequencePresentationMove = { index: number, san: string, board: MoveSequencePresentationBoard, };
