// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Piece } from "./Piece.js";
import type { Square } from "./Square.js";

export type OccupiedSquare = { square: Square, piece: Piece, };
