// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LearningResourceMappingId } from "./LearningResourceMappingId.js";
import type { OpeningMetadata } from "./OpeningMetadata.js";
import type { PositionPhase } from "./PositionPhase.js";

export type OpeningLearningEvidence = { positionPhase: PositionPhase, openingIdentification: OpeningMetadata, resourceMappingId: LearningResourceMappingId, };
