// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlternativeMoveEvaluation } from "./AlternativeMoveEvaluation.js";
import type { Color } from "./Color.js";

export type OpeningAnalyzedPly = { index: number, moveUci: string, mover: Color, evaluation: AlternativeMoveEvaluation, resultingFen: string, };
