// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpeningLineFindMatch } from "./OpeningLineFindMatch.js";
import type { OpeningLineFindTruncation } from "./OpeningLineFindTruncation.js";

export type OpeningLineFindResult = { matches: Array<OpeningLineFindMatch>, truncation: OpeningLineFindTruncation, };
