// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpeningIdentificationProvenance } from "./OpeningIdentificationProvenance.js";

export type OpeningMetadata = { "kind": "present", eco: string, name: string, provenance: OpeningIdentificationProvenance, } | { "kind": "absent" };
