// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpeningCatalogVersion } from "./OpeningCatalogVersion.js";
import type { OpeningServiceAttribution } from "./OpeningServiceAttribution.js";
import type { OpeningServiceProvider } from "./OpeningServiceProvider.js";

export type OpeningIdentificationProvenance = { "kind": "service", provider: OpeningServiceProvider, attribution: OpeningServiceAttribution, } | { "kind": "catalog", catalogVersion: OpeningCatalogVersion, matchedPly: number, };
