// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineEvaluation } from "./EngineEvaluation.js";

export type OpeningAnalyzedRoot = { fen: string, evaluation: EngineEvaluation, };
