// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveInput } from "./MoveInput.js";

export type OpeningAnalysisRequest = { openingLineRef: string, continuation: Array<MoveInput>, };
