// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpeningAnalyzedPly } from "./OpeningAnalyzedPly.js";
import type { OpeningAnalyzedRoot } from "./OpeningAnalyzedRoot.js";
import type { OpeningContinuationVerdict } from "./OpeningContinuationVerdict.js";
import type { OpeningLineIdentity } from "./OpeningLineIdentity.js";
import type { RetryDirective } from "./RetryDirective.js";

export type OpeningAnalysisOutcome = { "outcome": "analyzed", line: OpeningLineIdentity, root: OpeningAnalyzedRoot, plies: Array<OpeningAnalyzedPly>, verdict: OpeningContinuationVerdict, } | { "outcome": "unknownOpeningLine" } | { "outcome": "rateLimited", retry: RetryDirective, } | { "outcome": "unavailable", retry: RetryDirective, };
