// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlternativeMoveProgressStage } from "./AlternativeMoveProgressStage.js";
import type { CoachTurnProgressStage } from "./CoachTurnProgressStage.js";
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { GameImportId } from "./GameImportId.js";
import type { HostTurnStepLabel } from "./HostTurnStepLabel.js";
import type { ImportProgressStage } from "./ImportProgressStage.js";
import type { ReviewMomentPreparationProgressStage } from "./ReviewMomentPreparationProgressStage.js";
import type { ReviewSessionProgressStage } from "./ReviewSessionProgressStage.js";

export type OperationProgress = { "kind": "import", stage: ImportProgressStage, } | { "kind": "reviewSession", stage: ReviewSessionProgressStage, } | { "kind": "reviewMomentPreparation", gameImportId: GameImportId, reviewMomentId: CriticalMomentId, stage: ReviewMomentPreparationProgressStage, } | { "kind": "alternativeMove", stage: AlternativeMoveProgressStage, } | { "kind": "alternativeMoveAllowance", remaining: number, } | { "kind": "coachTurn", stage: CoachTurnProgressStage, } | { "kind": "hostTurn", label: HostTurnStepLabel, };
