// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { PieceRole } from "./PieceRole.js";
import type { Square } from "./Square.js";

export type PieceAtSquare = { color: Color, role: PieceRole, square: Square, };
