// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineEvaluation } from "./EngineEvaluation.js";
import type { PositionSnapshot } from "./PositionSnapshot.js";

export type PlayerPlanEvaluationFacts = { positionSnapshot: PositionSnapshot, textBoard: string, reviewedMoveSan: string, objectiveCounterplaySan: Array<string>, bestMoveEvaluation: EngineEvaluation, playedMoveEvaluation: EngineEvaluation, };
