// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactDigest } from "./ArtifactDigest.js";
import type { PlayerPlanEvaluationFacts } from "./PlayerPlanEvaluationFacts.js";

export type PlayerPlanEvaluationContext = { factsRef: ArtifactDigest, facts: PlayerPlanEvaluationFacts, };
