// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyCoachingProvider } from "./DailyCoachingProvider.js";
import type { PlayingProfileConnectionStatus } from "./PlayingProfileConnectionStatus.js";

export type PlayingProfileConnection = { provider: DailyCoachingProvider, username: string, canonicalUrl: string, status: PlayingProfileConnectionStatus, };
