// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayedOpeningAggregate = { eco: string, name: string, playCount: number, lastPlayedAtUnixMilliseconds: number, openingLineRef?: string, path?: string, };
