// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactDigest } from "./ArtifactDigest.js";

export type PlayerPlanEvaluationDraft = { factsRef: ArtifactDigest, text: string, };
