// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetadataText } from "./MetadataText.js";
import type { RatingMetadata } from "./RatingMetadata.js";

export type PlayerMetadata = { name: MetadataText, rating: RatingMetadata, };
