// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayedOpeningAggregate } from "./PlayedOpeningAggregate.js";

export type PlayedOpeningsResult = { openings: Array<PlayedOpeningAggregate>, };
