// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardTerminalOutcome } from "./BoardTerminalOutcome.js";
import type { EngineEvaluation } from "./EngineEvaluation.js";
import type { GameReviewResidualOutcome } from "./GameReviewResidualOutcome.js";

export type PlayedMoveOutcomeEvidence = { "kind": "analyzed", playedEvaluation: EngineEvaluation, centipawnLoss: number | null, residualOutcome: GameReviewResidualOutcome, } | { "kind": "terminal", outcome: BoardTerminalOutcome, };
