// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlternativeMoveId } from "./AlternativeMoveId.js";

export type PositionInspectionTarget = { "kind": "reviewedMove" } | { "kind": "alternativeMove", alternativeMoveId: AlternativeMoveId, };
