// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { DrawClaimState } from "./DrawClaimState.js";
import type { DrawReason } from "./DrawReason.js";

export type PositionStatus = { "kind": "ongoing", drawClaims: DrawClaimState, } | { "kind": "checkmate", winner: Color, } | { "kind": "draw", reason: DrawReason, };
