// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositionPhaseKind } from "./PositionPhaseKind.js";
import type { PositionPhasePolicyVersion } from "./PositionPhasePolicyVersion.js";

export type PositionPhase = { policyVersion: PositionPhasePolicyVersion, phase: PositionPhaseKind, };
