// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameReviewMechanismPayoff } from "./GameReviewMechanismPayoff.js";
import type { GameReviewPieceRole } from "./GameReviewPieceRole.js";

export type PositiveHighlightAchievement = { "kind": "completedCheckmate" } | { "kind": "capturedPiece", role: GameReviewPieceRole, square: string, } | { "kind": "advancedPassedPawn", toSquare: string, } | { "kind": "tacticalPayoff", payoff: GameReviewMechanismPayoff, };
