// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoachTurnContext } from "./CoachTurnContext.js";
import type { Color } from "./Color.js";
import type { EngineEvaluation } from "./EngineEvaluation.js";
import type { PositionSnapshot } from "./PositionSnapshot.js";
import type { ReviewSessionEvidencePacket } from "./ReviewSessionEvidencePacket.js";

export type PositionInspection = { positionSnapshot: PositionSnapshot, textBoard: string, sideToMove: Color, evaluation: EngineEvaluation, context: CoachTurnContext, evidencePacket: ReviewSessionEvidencePacket, };
