// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositiveHighlightAchievement } from "./PositiveHighlightAchievement.js";
import type { PositiveHighlightQualificationReason } from "./PositiveHighlightQualificationReason.js";

export type PositiveHighlightQualification = { reasons: Array<PositiveHighlightQualificationReason>, achievements: Array<PositiveHighlightAchievement>, };
