// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EloRelativeQualificationReason } from "./EloRelativeQualificationReason.js";
import type { EloRelativeStrength } from "./EloRelativeStrength.js";
import type { ObjectiveExcellenceReason } from "./ObjectiveExcellenceReason.js";

export type PositiveHighlightQualificationReason = { "lane": "objective", reason: ObjectiveExcellenceReason, } | { "lane": "eloRelative", reason: EloRelativeQualificationReason, strength: EloRelativeStrength, };
