// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PieceAtSquare } from "./PieceAtSquare.js";

export type PositionGoal = { "kind": "gainMaterial", targets: Array<PieceAtSquare>, };
