// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactDigest } from "./ArtifactDigest.js";
import type { CastlingRights } from "./CastlingRights.js";
import type { Color } from "./Color.js";
import type { EnPassantState } from "./EnPassantState.js";
import type { OccupiedSquare } from "./OccupiedSquare.js";
import type { PositionRef } from "./PositionRef.js";
import type { PositionStatus } from "./PositionStatus.js";
import type { PositionVariant } from "./PositionVariant.js";
import type { RepetitionState } from "./RepetitionState.js";

export type PositionSnapshot = { positionRef: PositionRef, variant: PositionVariant, fen: string, occupied: Array<OccupiedSquare>, sideToMove: Color, castlingRights: CastlingRights, enPassant: EnPassantState, halfmoveClock: number, fullmoveNumber: number, repetition: RepetitionState, status: PositionStatus, historyDigest: ArtifactDigest, };
