// @generated by generate_review_session_contract; do not edit.

import { ray } from "chessops/attacks"
import { Chess, isStandardMaterial } from "chessops/chess"
import { makeFen, parseFen } from "chessops/fen"

import type { PositionSnapshot } from "./PositionSnapshot.js"
import {
  assertDigest,
  ContractDecodeError,
  sameCanonicalJson,
} from "./contract-runtime.js"

type ParsedOccupiedSquare = {
  square: string
  piece: { color: "white" | "black"; role: string }
}

export async function validatePositionSnapshot(
  position: PositionSnapshot,
): Promise<void> {
  validateCanonicalPositionFields(position)
  const { positionRef, ...content } = position
  await assertDigest(positionRef, content, "$.positionRef")
}

function validateCanonicalPositionFields(position: PositionSnapshot): void {
  const fields = position.fen.split(" ")
  if (fields.length !== 6) {
    throw new ContractDecodeError("$.fen", "must be a canonical six-field FEN")
  }
  const [
    boardField,
    sideField,
    castlingField,
    enPassantField,
    halfmoveField,
    fullmoveField,
  ] = fields as [string, string, string, string, string, string]
  const setupResult = parseFen(
    `${boardField} ${sideField} ${castlingField} ${enPassantField} 0 1`,
  )
  if (setupResult.isErr) {
    throw new ContractDecodeError(
      "$.fen",
      "is not a legal standard-chess position",
    )
  }
  const chessResult = Chess.fromSetup(setupResult.value)
  if (chessResult.isErr) {
    throw new ContractDecodeError(
      "$.fen",
      "is not a legal standard-chess position",
    )
  }
  const chess = chessResult.value
  if (isImpossibleCheckByRustRules(chess) || !isStandardMaterial(chess)) {
    throw new ContractDecodeError(
      "$.fen",
      "cannot arise in a standard chess game",
    )
  }
  const canonicalRuleFields = makeFen(chess.toSetup())
    .split(" ")
    .slice(0, 4)
    .join(" ")
  if (canonicalRuleFields !== fields.slice(0, 4).join(" ")) {
    throw new ContractDecodeError(
      "$.fen",
      "is not canonical under legal chess rules",
    )
  }
  const ranks = boardField.split("/")
  if (ranks.length !== 8) {
    throw new ContractDecodeError("$.fen", "must contain eight ranks")
  }

  const occupied: ParsedOccupiedSquare[] = []
  const roleByFen: Readonly<Record<string, string>> = {
    p: "pawn",
    n: "knight",
    b: "bishop",
    r: "rook",
    q: "queen",
    k: "king",
  }
  for (const [rankIndex, rank] of ranks.entries()) {
    let file = 0
    let empty = 0
    let canonicalRank = ""
    for (const token of rank) {
      if (/^[1-8]$/.test(token)) {
        const count = Number(token)
        file += count
        empty += count
        continue
      }
      const role = roleByFen[token.toLowerCase()]
      if (role === undefined || file >= 8) {
        throw new ContractDecodeError(
          "$.fen",
          "contains an invalid board token",
        )
      }
      if (empty > 0) canonicalRank += String(empty)
      empty = 0
      canonicalRank += token
      occupied.push({
        square: `${String.fromCharCode(97 + file)}${8 - rankIndex}`,
        piece: {
          color: token === token.toUpperCase() ? "white" : "black",
          role,
        },
      })
      file += 1
    }
    if (empty > 0) canonicalRank += String(empty)
    if (file !== 8 || canonicalRank !== rank) {
      throw new ContractDecodeError(
        "$.fen",
        "contains a non-canonical board rank",
      )
    }
  }
  occupied.sort(
    (left, right) => squareIndex(left.square) - squareIndex(right.square),
  )
  if (!sameCanonicalJson(position.occupied, occupied)) {
    throw new ContractDecodeError("$.occupied", "does not match the FEN board")
  }

  const sideToMove =
    sideField === "w" ? "white" : sideField === "b" ? "black" : undefined
  if (sideToMove === undefined || position.sideToMove !== sideToMove) {
    throw new ContractDecodeError("$.sideToMove", "does not match the FEN")
  }
  const castlingRights = {
    whiteKingSide: castlingField.includes("K"),
    whiteQueenSide: castlingField.includes("Q"),
    blackKingSide: castlingField.includes("k"),
    blackQueenSide: castlingField.includes("q"),
  }
  const canonicalCastling =
    `${castlingRights.whiteKingSide ? "K" : ""}${castlingRights.whiteQueenSide ? "Q" : ""}${castlingRights.blackKingSide ? "k" : ""}${castlingRights.blackQueenSide ? "q" : ""}` ||
    "-"
  if (
    castlingField !== canonicalCastling ||
    !sameCanonicalJson(position.castlingRights, castlingRights)
  ) {
    throw new ContractDecodeError(
      "$.castlingRights",
      "does not match canonical FEN rights",
    )
  }
  if (!hasStandardCastlingPieces(occupied, castlingRights)) {
    throw new ContractDecodeError(
      "$.castlingRights",
      "requires the standard king and rook squares",
    )
  }
  const enPassant =
    enPassantField === "-"
      ? { kind: "none" }
      : { kind: "available", square: enPassantField }
  if (!sameCanonicalJson(position.enPassant, enPassant)) {
    throw new ContractDecodeError(
      "$.enPassant",
      "does not match the legal FEN target",
    )
  }
  if (
    !/^(0|[1-9][0-9]*)$/.test(halfmoveField) ||
    Number(halfmoveField) !== position.halfmoveClock
  ) {
    throw new ContractDecodeError("$.halfmoveClock", "does not match the FEN")
  }
  if (
    !/^[1-9][0-9]*$/.test(fullmoveField) ||
    Number(fullmoveField) !== position.fullmoveNumber
  ) {
    throw new ContractDecodeError("$.fullmoveNumber", "does not match the FEN")
  }
  validatePositionRuleState(position, chess)
}

function isImpossibleCheckByRustRules(chess: Chess): boolean {
  const king = chess.board.kingOf(chess.turn)
  if (king === undefined) return false
  const attacker = chess.turn === "white" ? "black" : "white"
  const checkers = chess.kingAttackers(king, attacker, chess.board.occupied)
  const first = checkers.first()
  const last = checkers.last()
  if (first === undefined || last === undefined) return false
  if (chess.epSquare !== undefined) {
    const pushedTo = chess.epSquare ^ 8
    const pushedFrom = chess.epSquare ^ 24
    return (
      first !== last ||
      (first !== pushedTo &&
        chess
          .kingAttackers(
            king,
            attacker,
            chess.board.occupied.without(pushedTo).with(pushedFrom),
          )
          .nonEmpty())
    )
  }
  return first !== last && (checkers.size() > 2 || ray(first, last).has(king))
}

function hasStandardCastlingPieces(
  occupied: readonly ParsedOccupiedSquare[],
  castling: PositionSnapshot["castlingRights"],
): boolean {
  const hasPiece = (square: string, color: string, role: string): boolean =>
    occupied.some(
      (entry) =>
        entry.square === square &&
        entry.piece.color === color &&
        entry.piece.role === role,
    )
  return (
    (!castling.whiteKingSide ||
      (hasPiece("e1", "white", "king") && hasPiece("h1", "white", "rook"))) &&
    (!castling.whiteQueenSide ||
      (hasPiece("e1", "white", "king") && hasPiece("a1", "white", "rook"))) &&
    (!castling.blackKingSide ||
      (hasPiece("e8", "black", "king") && hasPiece("h8", "black", "rook"))) &&
    (!castling.blackQueenSide ||
      (hasPiece("e8", "black", "king") && hasPiece("a8", "black", "rook")))
  )
}

function squareIndex(square: string): number {
  return (Number(square[1]) - 1) * 8 + square.charCodeAt(0) - 97
}

function validatePositionRuleState(
  position: PositionSnapshot,
  chess: Chess,
): void {
  const occurrences =
    position.repetition.kind === "firstOccurrence"
      ? 1
      : position.repetition.occurrences
  if (
    (position.repetition.kind === "repeated" && occurrences !== 2) ||
    (position.repetition.kind === "drawClaimAvailable" && occurrences < 3)
  ) {
    throw new ContractDecodeError(
      "$.repetition",
      "has invalid occurrence semantics",
    )
  }
  const forcedStatus = chess.isCheckmate()
    ? {
        kind: "checkmate",
        winner: position.sideToMove === "white" ? "black" : "white",
      }
    : chess.isStalemate()
      ? { kind: "draw", reason: "stalemate" }
      : chess.isInsufficientMaterial()
        ? { kind: "draw", reason: "insufficientMaterial" }
        : occurrences >= 5
          ? { kind: "draw", reason: "fivefoldRepetition" }
          : position.halfmoveClock >= 150
            ? { kind: "draw", reason: "seventyFiveMoveRule" }
            : undefined
  if (forcedStatus !== undefined) {
    if (!sameCanonicalJson(position.status, forcedStatus)) {
      throw new ContractDecodeError(
        "$.status",
        "does not match the forced game status",
      )
    }
    return
  }

  const expectedClaims: string[] = []
  if (occurrences >= 3) expectedClaims.push("threefoldRepetition")
  if (position.halfmoveClock >= 100) expectedClaims.push("fiftyMoveRule")
  if (position.status.kind === "ongoing") {
    const actualClaims =
      position.status.drawClaims.kind === "none"
        ? []
        : [position.status.drawClaims.first, ...position.status.drawClaims.rest]
    if (!sameCanonicalJson(actualClaims, expectedClaims)) {
      throw new ContractDecodeError(
        "$.status.drawClaims",
        "does not match rule state",
      )
    }
    return
  }
  const isPermittedDraw =
    position.status.kind === "draw" &&
    (position.status.reason === "agreement" ||
      (position.status.reason === "threefoldRepetition" && occurrences >= 3) ||
      (position.status.reason === "fiftyMoveRule" &&
        position.halfmoveClock >= 100))
  if (!isPermittedDraw) {
    throw new ContractDecodeError("$.status", "does not match rule state")
  }
}
