// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionCandidateRef } from "./DecisionCandidateRef.js";
import type { EngineComparison } from "./EngineComparison.js";
import type { SemanticComparison } from "./SemanticComparison.js";

export type PreferenceProof = { preferredCandidateRef: DecisionCandidateRef, engineComparisons: Array<EngineComparison>, semanticComparisons: Array<SemanticComparison>, };
