// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoachTurnId } from "./CoachTurnId.js";

export type PriorCoachTurn = { "kind": "none" } | { "kind": "steers", coachTurnId: CoachTurnId, } | { "kind": "retriesUnavailable", coachTurnId: CoachTurnId, };
