// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Probability } from "./Probability.js";

export type ProbabilityState = { "kind": "available", probability: Probability, } | { "kind": "unavailable" };
