// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceProvenance } from "./EvidenceProvenance.js";
import type { ImportProvenance } from "./ImportProvenance.js";

export type ProvenanceFact = { "kind": "import", source: ImportProvenance, } | { "kind": "provider", provider: EvidenceProvenance, };
