// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind.js";

export type ProviderUnavailableReason = { "kind": "lichessTransport" } | { "kind": "chessComTransport" } | { "kind": "stockfishProcess" } | { "kind": "maiaTransport" } | { "kind": "languageLayer" } | { "kind": "persistence" } | { "kind": "coachEngineTransport" } | { "kind": "timeout", provider: ProviderKind, } | { "kind": "rateLimited", retryAfterSeconds: number, } | { "kind": "queueDeadline" } | { "kind": "admissionLimit" };
