// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateGap } from "./CandidateGap.js";
import type { DecisionEngineProvenance } from "./DecisionEngineProvenance.js";

/**
 * An alternative root the MultiPV search ranked below the best move.
 *
 * It carries no absolute evaluation. MultiPV's scores are only mutually
 * comparable **within** its own search, so an alternative states how far behind
 * the best move it fell there, and nothing about its own worth.
 */
export type RankedAlternativeEvidence = { rank: number, rootMoveUci: string, gap: CandidateGap, variation: Array<string>, provenance: DecisionEngineProvenance, };
