// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyCoachingProvider } from "./DailyCoachingProvider.js";
import type { DailyCoachingReviewSide } from "./DailyCoachingReviewSide.js";

export type RecentPlayingProfileGame = { source: string, reviewSide: DailyCoachingReviewSide, provider: DailyCoachingProvider, endedAtUnixMilliseconds?: number, };
