// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyCoachingUnavailableReason } from "./DailyCoachingUnavailableReason.js";
import type { RecentPlayingProfileGame } from "./RecentPlayingProfileGame.js";
import type { RetryDirective } from "./RetryDirective.js";

export type RecentPlayingProfileGamesOutcome = { "outcome": "found", games: Array<RecentPlayingProfileGame>, } | { "outcome": "noPlayingProfile" } | { "outcome": "unavailable", reason: DailyCoachingUnavailableReason, retry: RetryDirective, };
