// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RejectionRecovery = { "kind": "correctInput" } | { "kind": "selectReviewSide" } | { "kind": "provideEloProfile" } | { "kind": "chooseLegalMove", matchingMoves: Array<string>, } | { "kind": "retryAfter", seconds: number, } | { "kind": "startNewReviewSession" } | { "kind": "none" };
