// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RepetitionState = { "kind": "firstOccurrence" } | { "kind": "repeated", occurrences: number, } | { "kind": "drawClaimAvailable", occurrences: number, };
