// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewSide } from "./ReviewSide.js";

export type RequestedReviewSide = { "kind": "selected", reviewSide: ReviewSide, } | { "kind": "fromQualifiedUrl" } | { "kind": "required" };
