// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EloRating } from "./EloRating.js";

export type RequestedEloProfile = { "kind": "playerProvided", rating: EloRating, } | { "kind": "fromImportedMetadata" };
