// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EloRating } from "./EloRating.js";
import type { EloSource } from "./EloSource.js";

export type ResolvedEloProfile = { rating: EloRating, source: EloSource, };
