// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpeningLineIdentity } from "./OpeningLineIdentity.js";

export type ResolveOpeningLineOutcome = { "outcome": "resolved", line: OpeningLineIdentity, } | { "outcome": "unknownOpeningLine" };
