// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RetryDirective = { "kind": "retryAllowed" } | { "kind": "retryAfter", seconds: number, } | { "kind": "startNewOperation" } | { "kind": "notRetryable" };
