// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameImportId } from "./GameImportId.js";
import type { ImportedGameOpening } from "./ImportedGameOpening.js";
import type { ImportedGameOutcome } from "./ImportedGameOutcome.js";
import type { ImportedGameProvider } from "./ImportedGameProvider.js";
import type { ImportedGameReviewSide } from "./ImportedGameReviewSide.js";
import type { ImportedGameTimeControlClass } from "./ImportedGameTimeControlClass.js";
import type { LearningTrackKey } from "./LearningTrackKey.js";

export type ReviewedGameSearchCard = { reviewedGameKey: string, gameImportId: GameImportId, provider: ImportedGameProvider, reviewSide: ImportedGameReviewSide, outcome: ImportedGameOutcome | null, opening: ImportedGameOpening | null, opponentName: string | null, opponentRating: number | null, endedAt?: string, timeControlClass: ImportedGameTimeControlClass | null, learningPathCount: number, learningTrackKeys: Array<LearningTrackKey>, digested: boolean, imported: boolean, digestId?: string | null, digestDate?: string | null, };
