// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositionSnapshot } from "./PositionSnapshot.js";
import type { ReviewMomentAuthoringReadiness } from "./ReviewMomentAuthoringReadiness.js";
import type { ReviewMomentClassificationKind } from "./ReviewMomentClassificationKind.js";
import type { ReviewMomentLearningMaterial } from "./ReviewMomentLearningMaterial.js";
import type { ReviewMomentOccurrence } from "./ReviewMomentOccurrence.js";

/**
 * One chronologically admitted Review Moment.
 *
 * Display facts remain available independently of the richer authoring core.
 * Delivery surfaces can therefore render the complete automatic set while
 * authoring preparation is still pending.
 */
export type ReviewSessionMoment = { reviewMoment: ReviewMomentOccurrence, positionSnapshot: PositionSnapshot, learningMaterial: ReviewMomentLearningMaterial, authoring: ReviewMomentAuthoringReadiness, 
/**
 * Extractor verdict kind. Player-Selected Moments need this on the wire so
 * surfaces can drop Neutral and render a nominated Positive Highlight or
 * Improvement Opportunity after resume.
 */
classificationKind: ReviewMomentClassificationKind | null, };
