// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewedGameSearchTruncation = { "kind": "complete", totalMatchCount: number, } | { "kind": "truncated", totalMatchCount: number, oldestReturnedAt: string, };
