// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewSessionPresentationPiece } from "./ReviewSessionPresentationPiece.js";
import type { ReviewSessionPresentationPieceMotion } from "./ReviewSessionPresentationPieceMotion.js";

export type ReviewSessionPresentationAnimationFrame = { index: number, moveLabel: string, durationMs: number, motions: Array<ReviewSessionPresentationPieceMotion>, removedPieceIds: Array<string>, placements: Array<ReviewSessionPresentationPiece>, };
