// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewedGameSearchCoverage = { reviewedGameCount: number, earliestPlayedAt?: string | null, latestPlayedAt?: string | null, };
