// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { GameImportId } from "./GameImportId.js";
import type { IdempotencyKey } from "./IdempotencyKey.js";
import type { ReviewMomentSelection } from "./ReviewMomentSelection.js";

export type ReviewSessionPresentationHandoffTarget = { gameImportId: GameImportId, momentId: CriticalMomentId, ply: number, selection: ReviewMomentSelection, idempotencyKey: IdempotencyKey, };
