// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeliverySurface } from "./DeliverySurface.js";
import type { OperationId } from "./OperationId.js";
import type { RequestId } from "./RequestId.js";
import type { ReviewSessionCommand } from "./ReviewSessionCommand.js";

export type ReviewSessionCommandEnvelope = { requestId: RequestId, operationId: OperationId, surface: DeliverySurface, command: ReviewSessionCommand, };
