// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanonicalGameMove } from "./CanonicalGameMove.js";
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { GameRef } from "./GameRef.js";
import type { ReviewMomentSelection } from "./ReviewMomentSelection.js";

export type ReviewMomentOccurrence = { momentId: CriticalMomentId, ply: number, precedingMove: CanonicalGameMove | null, selection: ReviewMomentSelection, gameRef: GameRef, };
