// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewedGameSearchCard } from "./ReviewedGameSearchCard.js";
import type { ReviewedGameSearchCoverage } from "./ReviewedGameSearchCoverage.js";
import type { ReviewedGameSearchTruncation } from "./ReviewedGameSearchTruncation.js";

export type ReviewedGameSearchResult = { games: Array<ReviewedGameSearchCard>, coverage: ReviewedGameSearchCoverage, truncation: ReviewedGameSearchTruncation, };
