// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameReviewCriticalMoment } from "./GameReviewCriticalMoment.js";

/**
 * The only facts boundary accepted by Review Moment comment authoring.
 *
 * Keeping the classification tag beside its source moment means every
 * downstream consumer can use one typed dispatch instead of attempting to
 * infer a teaching mode from optional fields.
 */
export type ReviewMomentCommentFacts = { "kind": "positive", moment: GameReviewCriticalMoment, } | { "kind": "improvement", moment: GameReviewCriticalMoment, } | { "kind": "neutral", moment: GameReviewCriticalMoment, };
