// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { EloRating } from "./EloRating.js";
import type { GameImportId } from "./GameImportId.js";
import type { OpeningMetadata } from "./OpeningMetadata.js";
import type { ReviewSessionPresentationAnimation } from "./ReviewSessionPresentationAnimation.js";
import type { ReviewSessionPresentationEvaluationPoint } from "./ReviewSessionPresentationEvaluationPoint.js";
import type { ReviewSessionPresentationHandoffState } from "./ReviewSessionPresentationHandoffState.js";
import type { ReviewSessionPresentationMoment } from "./ReviewSessionPresentationMoment.js";
import type { ReviewSessionPresentationSource } from "./ReviewSessionPresentationSource.js";
import type { ReviewSessionPresentationVersion } from "./ReviewSessionPresentationVersion.js";
import type { ReviewSide } from "./ReviewSide.js";

export type ReviewSessionPresentation = { version: ReviewSessionPresentationVersion, gameImportId: GameImportId, sessionRevision: number, presentationRevision: number, source: ReviewSessionPresentationSource, opening: OpeningMetadata, reviewSide: ReviewSide, eloRating: EloRating, orientation: Color, selectedMomentId: CriticalMomentId | null, maxPly: number, evaluationTimeline: Array<ReviewSessionPresentationEvaluationPoint>, moments: Array<ReviewSessionPresentationMoment>, handoffState: ReviewSessionPresentationHandoffState, animation?: ReviewSessionPresentationAnimation | null, };
