// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An optional classification constraint on a forward Review Moment reference.
 */
export type ReviewMomentReferenceClassification = "improvementOpportunity";
