// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { GameImportId } from "./GameImportId.js";
import type { ReviewSessionPresentationAnimation } from "./ReviewSessionPresentationAnimation.js";
import type { ReviewSessionPresentationChangedField } from "./ReviewSessionPresentationChangedField.js";
import type { ReviewSessionPresentationMoment } from "./ReviewSessionPresentationMoment.js";
import type { ReviewSessionPresentationVersion } from "./ReviewSessionPresentationVersion.js";

export type ReviewSessionPresentationAddition = { version: ReviewSessionPresentationVersion, gameImportId: GameImportId, priorRevision: number, resultingRevision: number, changedMomentIds: Array<CriticalMomentId>, changedFields: Array<ReviewSessionPresentationChangedField>, fullRefreshRequired: boolean, moment: ReviewSessionPresentationMoment, animation?: ReviewSessionPresentationAnimation | null, };
