// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandRejectionReason } from "./CommandRejectionReason.js";
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { GameImportId } from "./GameImportId.js";
import type { OperationCompletion } from "./OperationCompletion.js";
import type { OperationConflictReason } from "./OperationConflictReason.js";
import type { OperationKind } from "./OperationKind.js";
import type { OperationProgress } from "./OperationProgress.js";
import type { ProviderUnavailableReason } from "./ProviderUnavailableReason.js";
import type { RejectionRecovery } from "./RejectionRecovery.js";
import type { RetryDirective } from "./RetryDirective.js";
import type { ReviewSessionLimits } from "./ReviewSessionLimits.js";

export type ReviewSessionEvent = { "kind": "accepted", operation: OperationKind, limits: ReviewSessionLimits, } | { "kind": "progress", stage: OperationProgress, } | { "kind": "completed", result: OperationCompletion, } | { "kind": "unavailable", operation: OperationKind, reason: ProviderUnavailableReason, retry: RetryDirective, } | { "kind": "reviewMomentUnavailable", gameImportId: GameImportId, reviewMomentId: CriticalMomentId, reason: ProviderUnavailableReason, retry: RetryDirective, } | { "kind": "cancelled", operation: OperationKind, } | { "kind": "conflict", operation: OperationKind, reason: OperationConflictReason, } | { "kind": "rejected", operation: OperationKind, reason: CommandRejectionReason, recovery: RejectionRecovery, };
