// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { DecisionExplanationRef } from "./DecisionExplanationRef.js";
import type { GameImportId } from "./GameImportId.js";
import type { GameReviewSnapshotSequence } from "./GameReviewSnapshotSequence.js";
import type { GameReviewSnapshotVersion } from "./GameReviewSnapshotVersion.js";
import type { GroundedExplanation } from "./GroundedExplanation.js";

/**
 * One Review Moment's detail, addressed under the review that contains it.
 *
 * A surface holding the snapshot already has how this moment looks; what it
 * reads here is what the moment can say — the continuations it offers played
 * out, and the resolved proof a host model may speak from. The proof aggregate
 * itself is a third address, never this one.
 */
export type ReviewMomentSnapshot = { version: GameReviewSnapshotVersion, gameImportId: GameImportId, reviewMomentId: CriticalMomentId, ply: number, orientation: Color, sequences: Array<GameReviewSnapshotSequence>, explanationRef?: DecisionExplanationRef | null, explanation?: GroundedExplanation | null, };
