// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color.js";
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { PositionRef } from "./PositionRef.js";

export type ReviewedMoveAnchor = { criticalMomentId: CriticalMomentId, ply: number, side: Color, positionRef: PositionRef, playedMoveUci: string, };
