// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoachTurnContext } from "./CoachTurnContext.js";
import type { ImportedGame } from "./ImportedGame.js";
import type { PositionSnapshot } from "./PositionSnapshot.js";
import type { RequestId } from "./RequestId.js";
import type { ReviewMomentOccurrence } from "./ReviewMomentOccurrence.js";
import type { ReviewSessionEvidencePacket } from "./ReviewSessionEvidencePacket.js";

export type ReviewSessionCoreContract = { requestId: RequestId, importedGame: ImportedGame, positionSnapshot: PositionSnapshot, reviewMoment: ReviewMomentOccurrence, coachTurnContext: CoachTurnContext, evidencePacket: ReviewSessionEvidencePacket, };
