// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositionRef } from "./PositionRef.js";
import type { ReviewSessionPresentationMove } from "./ReviewSessionPresentationMove.js";
import type { ReviewSessionPresentationPiece } from "./ReviewSessionPresentationPiece.js";
import type { Square } from "./Square.js";

export type ReviewSessionPresentationBoard = { positionRef: PositionRef, pieces: Array<ReviewSessionPresentationPiece>, lastMove: ReviewSessionPresentationMove | null, checkSquare: Square | null, announcement: string, };
