// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CriticalMomentId } from "./CriticalMomentId.js";

export type ReviewSessionRevisionDelta = { priorRevision: number, resultingRevision: number, changedMomentIds: Array<CriticalMomentId>, fullRefreshRequired: boolean, };
