// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { DecisionLearningOutcome } from "./DecisionLearningOutcome.js";
import type { GameReviewEvaluationDisplay } from "./GameReviewEvaluationDisplay.js";
import type { ReviewMomentLearningMaterial } from "./ReviewMomentLearningMaterial.js";
import type { ReviewSessionPresentationArrow } from "./ReviewSessionPresentationArrow.js";
import type { ReviewSessionPresentationAuthoringReadiness } from "./ReviewSessionPresentationAuthoringReadiness.js";
import type { ReviewSessionPresentationBoard } from "./ReviewSessionPresentationBoard.js";
import type { ReviewSessionPresentationHandoffTarget } from "./ReviewSessionPresentationHandoffTarget.js";
import type { ReviewSessionPresentationMomentKind } from "./ReviewSessionPresentationMomentKind.js";
import type { ReviewSessionPresentationMomentTone } from "./ReviewSessionPresentationMomentTone.js";

export type ReviewSessionPresentationMoment = { momentId: CriticalMomentId, ply: number, moveLabel: string, kind: ReviewSessionPresentationMomentKind, authoringReadiness: ReviewSessionPresentationAuthoringReadiness, tone: ReviewSessionPresentationMomentTone, glyph: string, title: string, summary: string, decisionLearningOutcome: DecisionLearningOutcome, learningMaterial: ReviewMomentLearningMaterial, board: ReviewSessionPresentationBoard, arrows: Array<ReviewSessionPresentationArrow>, playedEvaluation: GameReviewEvaluationDisplay, bestEvaluation: GameReviewEvaluationDisplay, handoff: ReviewSessionPresentationHandoffTarget, };
