// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies exactly what a Game Review read would answer with.
 *
 * A client cache holds bytes it cannot otherwise date: the frozen review
 * is immutable, but the *derivation* over it is not, and neither is the
 * comment template a Review Moment's prose was written from. This digest
 * folds both, so a caller can offer what it already holds and be told it
 * is still current instead of being sent the payload again.
 */
export type ReviewContentDigest = string & { readonly __brand: "ReviewContentDigest" };
