// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { ReviewMomentReferenceClassification } from "./ReviewMomentReferenceClassification.js";

/**
 * How a Player named the Review Moment they want opened.
 *
 * Distinct from [`ReviewMomentSelection`], which every resolved occurrence
 * carries as its provenance: this is only the ask, and `Next` names no moment
 * at all until the ply-ordered review is consulted. Keeping the ask separate
 * from what it resolves to is what lets one tool serve "this Critical Moment",
 * "the move on ply 27 that nothing flagged", "whatever comes after this one",
 * and "the next Improvement Opportunity" without the caller resolving or
 * filtering anything itself.
 */
export type ReviewMomentReference = { "kind": "critical", reviewMomentId: CriticalMomentId, } | { "kind": "ply", ply: number, } | { "kind": "next", afterReviewMomentId?: CriticalMomentId | null, classification?: ReviewMomentReferenceClassification | null, };
