// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CriticalMomentId } from "./CriticalMomentId.js";
import type { ReviewSessionPresentationAnimationFrame } from "./ReviewSessionPresentationAnimationFrame.js";
import type { ReviewSessionPresentationVersion } from "./ReviewSessionPresentationVersion.js";

export type ReviewSessionPresentationAnimation = { version: ReviewSessionPresentationVersion, lineId: string, reviewMomentId: CriticalMomentId, frames: Array<ReviewSessionPresentationAnimationFrame>, };
