// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewSessionLimits = { maxCommittedAlternativeMoves: number, maxBranchDepthPlies: number, maxStartedCoachTurns: number, maxPlayerMessageBytes: number, maxPgnBytes: number, maxActiveCoachTurns: number, maxActiveAlternativeMoveEvaluations: number, stockfishSlots: number, maxPositionInspectionsPerTurn: number, maxHostTurnPriorTurns: number, };
