// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewSessionPresentationArrowKind } from "./ReviewSessionPresentationArrowKind.js";
import type { Square } from "./Square.js";

export type ReviewSessionPresentationArrow = { kind: ReviewSessionPresentationArrowKind, from: Square, to: Square, label: string, };
