// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CriticalMomentGroundingLedger } from "./CriticalMomentGroundingLedger.js";
import type { CriticalMomentIntentAuthoringContext } from "./CriticalMomentIntentAuthoringContext.js";
import type { ReviewMomentCommentFacts } from "./ReviewMomentCommentFacts.js";

/**
 * Complete immutable authority a host Language Layer needs to author one
 * Review Moment comment without recreating the Review Engine's grounding policy.
 */
export type ReviewMomentCommentAuthoringContext = { facts: ReviewMomentCommentFacts, intent?: CriticalMomentIntentAuthoringContext | null, requiredGroundingLedger: CriticalMomentGroundingLedger, };
