// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LearningPlanSelectionPolicyVersion } from "./LearningPlanSelectionPolicyVersion.js";
import type { LearningResourceCatalogVersion } from "./LearningResourceCatalogVersion.js";
import type { LearningTrack } from "./LearningTrack.js";

export type ReviewMomentLearningMaterial = { selectionPolicyVersion: LearningPlanSelectionPolicyVersion, resourceCatalogVersion: LearningResourceCatalogVersion, tracks: Array<LearningTrack>, };
