// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportedGameOutcome } from "./ImportedGameOutcome.js";
import type { ImportedGameProvider } from "./ImportedGameProvider.js";
import type { ImportedGameReviewSide } from "./ImportedGameReviewSide.js";
import type { ImportedGameTimeControlClass } from "./ImportedGameTimeControlClass.js";

export type ReviewedGameSearchRequest = { playedFrom?: string, playedTo?: string, provider?: ImportedGameProvider, openingEcoPrefix?: string, openingName?: string, outcome?: ImportedGameOutcome, reviewSide?: ImportedGameReviewSide, timeControlClass?: ImportedGameTimeControlClass, opponentName?: string, opponentRatingMin?: number, opponentRatingMax?: number, };
