// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationId } from "./OperationId.js";
import type { RequestId } from "./RequestId.js";
import type { ReviewSessionEvent } from "./ReviewSessionEvent.js";

export type ReviewSessionEventEnvelope = { requestId: RequestId, operationId: OperationId, sequence: number, event: ReviewSessionEvent, };
