// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomicFactRef } from "./AtomicFactRef.js";
import type { DecisionTerminalState } from "./DecisionTerminalState.js";
import type { MaterialValuePolicyVersion } from "./MaterialValuePolicyVersion.js";
import type { PieceAtSquare } from "./PieceAtSquare.js";
import type { PieceRole } from "./PieceRole.js";
import type { Square } from "./Square.js";

export type SemanticOutcomeData = { "kind": "materialBalanceChanged", conventionalValueDelta: number, valuePolicyVersion: MaterialValuePolicyVersion, gained: Array<PieceAtSquare>, lost: Array<PieceAtSquare>, } | { "kind": "pawnProgressed", pawn: PieceAtSquare, fromSquare: Square, toSquare: Square, promotionRole: PieceRole | null, beforeFrontSpanRef: AtomicFactRef, afterFrontSpanRef: AtomicFactRef | null, } | { "kind": "materialConfigurationChanged", beforeInventoryRefs: Array<AtomicFactRef>, afterInventoryRefs: Array<AtomicFactRef>, } | { "kind": "terminalStateReached", beforeStateRef: AtomicFactRef, afterStateRef: AtomicFactRef, result: DecisionTerminalState, } | { "kind": "attackAccessChanged", beforeAttackRef: AtomicFactRef, afterAttackRef: AtomicFactRef, addedSquares: Array<Square>, removedSquares: Array<Square>, } | { "kind": "checkStateChanged", beforeCheckersRef: AtomicFactRef, afterCheckersRef: AtomicFactRef, addedCheckers: Array<PieceAtSquare>, removedCheckers: Array<PieceAtSquare>, } | { "kind": "kingZonePressureChanged", beforePressureRef: AtomicFactRef, afterPressureRef: AtomicFactRef, addedAttackers: Array<PieceAtSquare>, removedAttackers: Array<PieceAtSquare>, };
