// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SemanticComparisonRelation } from "./SemanticComparisonRelation.js";
import type { SemanticOutcomeRef } from "./SemanticOutcomeRef.js";

export type SemanticComparison = { preferredOutcomeRef: SemanticOutcomeRef, alternativeOutcomeRef: SemanticOutcomeRef, relation: SemanticComparisonRelation, };
