// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtomicFactRef } from "./AtomicFactRef.js";
import type { SemanticOutcomeData } from "./SemanticOutcomeData.js";
import type { SemanticOutcomeRef } from "./SemanticOutcomeRef.js";

export type SemanticOutcome = { outcomeRef: SemanticOutcomeRef, data: SemanticOutcomeData, supportingFactRefs: Array<AtomicFactRef>, };
